
// Seletores do DOM
const createElementBtn = document.getElementById('createElementBtn');
const clearAllBtn = document.getElementById('clearAllBtn');
const dynamicStage = document.getElementById('dynamicStage');
const stagePlaceholder = document.getElementById('stagePlaceholder');
const elementCounter = document.getElementById('elementCounter');

const elementTypeInput = document.getElementById('elementType');
const elementTextInput = document.getElementById('elementText');
const elementThemeInput = document.getElementById('elementTheme');
const animToggleInput = document.getElementById('animToggle');

// Contador de elementos ativos
let activeCount = 0;

// 1. EVENTO DE CLIQUE PARA CRIAR ELEMENTOS DINAMICAMENTE
if (createElementBtn) {
    createElementBtn.addEventListener('click', () => {
            const type = elementTypeInput.value;
                    const text = elementTextInput.value.trim() || 'Elemento Sem Título';
                            const theme = elementThemeInput.value;
                                    const animation = animToggleInput.value;

                                            // Remover placeholder se for o primeiro elemento
                                                    if (stagePlaceholder && stagePlaceholder.parentNode) {
                                                                stagePlaceholder.remove();
                                                                        }

                                                                                // 2. CRIAÇÃO DE ELEMENTO VIA JAVASCRIPT (document.createElement)
                                                                                        const newCard = document.createElement('div');
                                                                                                
                                                                                                        // 3. ADICIONANDO CLASSES VIA JAVASCRIPT (.classList.add)
                                                                                                                newCard.classList.add('dyn-card', `theme-${theme}`);

                                                                                                                        // Aplicando classes de animação dinamicamente
                                                                                                                                if (animation === 'pulse') newCard.classList.add('anim-pulse');
                                                                                                                                        if (animation === 'slide') newCard.classList.add('anim-slide');
                                                                                                                                                if (animation === 'zoom') newCard.classList.add('anim-zoom');

                                                                                                                                                        // 4. ALTERANDO ESTILOS VIA JAVASCRIPT (element.style)
                                                                                                                                                                // Adicionando um ID único e manipulando estilos inline programaticamente
                                                                                                                                                                        const uniqueId = 'dyn_' + Date.now();
                                                                                                                                                                                newCard.id = uniqueId;
                                                                                                                                                                                        newCard.style.cursor = 'pointer';

                                                                                                                                                                                                // Definindo estrutura interna com template literals
                                                                                                                                                                                                        newCard.innerHTML = `
                                                                                                                                                                                                                    <div class="dyn-content">
                                                                                                                                                                                                                                    <i class="fa-solid fa-terminal"></i>
                                                                                                                                                                                                                                                    <span>[${type.toUpperCase()}] ${escapeHTML(text)}</span>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                            <button class="btn-remove-dyn" title="Remover elemento" data-id="${uniqueId}">
                                                                                                                                                                                                                                                                                            <i class="fa-solid fa-trash-can"></i>
                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                `;

                                                                                                                                                                                                                                                                                                                        // 5. ADIÇÃO DE EVENTOS CUSTOMIZADOS (click, mouseenter, mouseleave)
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                        // Evento de clique no card para demonstrar alteração de estilo in-line via JS
                                                                                                                                                                                                                                                                                                                                                newCard.addEventListener('click', (e) => {
                                                                                                                                                                                                                                                                                                                                                            // Evitar conflito se clicar no botão de remover
                                                                                                                                                                                                                                                                                                                                                                        if (e.target.closest('.btn-remove-dyn')) return;

                                                                                                                                                                                                                                                                                                                                                                                    // Manipulando style via JS dinamicamente ao clicar
                                                                                                                                                                                                                                                                                                                                                                                                const currentBg = newCard.style.backgroundColor;
                                                                                                                                                                                                                                                                                                                                                                                                            if (!currentBg || currentBg === 'transparent') {
                                                                                                                                                                                                                                                                                                                                                                                                                            newCard.style.backgroundColor = 'rgba(0, 243, 255, 0.08)';
                                                                                                                                                                                                                                                                                                                                                                                                                                            newCard.style.boxShadow = '0 0 20px var(--neon-cyan)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        newCard.style.backgroundColor = 'transparent';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        newCard.style.boxShadow = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Evento de hover (mouseenter / mouseleave) alterando estilos em tempo real
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            newCard.addEventListener('mouseenter', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        newCard.style.transform = 'scale(1.02) translateX(6px)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        newCard.addEventListener('mouseleave', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    newCard.style.transform = 'scale(1) translateX(0)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Evento do botão interno para REMOÇÃO DE ELEMENTO (Node.remove())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const removeBtn = newCard.querySelector('.btn-remove-dyn');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    removeBtn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Efeito visual de saída antes de remover
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            newCard.style.transform = 'scale(0.8)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        newCard.style.opacity = '0';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    newCard.remove(); // Removendo elemento do DOM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    activeCount--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    updateCounter();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    checkEmptyStage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }, 250);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Inserindo o novo elemento no palco (DOM Insertion)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dynamicStage.appendChild(newCard);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        activeCount++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                updateCounter();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Limpar campo de texto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elementTextInput.value = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elementTextInput.focus();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 6. EVENTO PARA REMOVER TODOS OS ELEMENTOS DO PALCO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (clearAllBtn) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clearAllBtn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const cards = dynamicStage.querySelectorAll('.dyn-card');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cards.forEach(card => card.remove());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                activeCount = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        updateCounter();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                checkEmptyStage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Função auxiliar para atualizar o contador visual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function updateCounter() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (elementCounter) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elementCounter.textContent = `Elementos Ativos: ${activeCount}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Função auxiliar para restaurar o placeholder caso o palco fique vazio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function checkEmptyStage() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (activeCount === 0 && dynamicStage) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!document.getElementById('stagePlaceholder')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dynamicStage.appendChild(stagePlaceholder);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Função de segurança contra XSS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function escapeHTML(str) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return str.replace(/[&<>'"]/g, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tag => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[tag] || tag)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }