function bemVindo() {

        document.body.innerHTML += `
                <div class="mensagem-foto" id="mensagemFoto">
                            <div class="caixa-foto">

                                            <img src="img/francisca.jpg" 
                                                                 alt="Foto da Francisca Allany">

                                                                                 <h2>💜 Seja muito bem-vindo!</h2>

                                                                                                 <p>
                                                                                                                     Você está no Blog da Francisca Allany!
                                                                                                                                     </p>

                                                                                                                                                     <button onclick="fecharFoto()">
                                                                                                                                                                         Fechar
                                                                                                                                                                                         </button>

                                                                                                                                                                                                     </div>
                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                 `;

                                                                                                                                                                                                                 }


                                                                                                                                                                                                                 function fecharFoto() {

                                                                                                                                                                                                                     let mensagem = document.getElementById("mensagemFoto");

                                                                                                                                                                                                                         if (mensagem) {
                                                                                                                                                                                                                                 mensagem.remove();
                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                     }


                                                                                                                                                                                                                                     function lerPost(tema) {

                                                                                                                                                                                                                                         alert(
                                                                                                                                                                                                                                                 "Você escolheu o post sobre " +
                                                                                                                                                                                                                                                         tema +
                                                                                                                                                                                                                                                                 "! 🚀\n\n" +
                                                                                                                                                                                                                                                                         "Em breve você poderá conferir o conteúdo completo."
                                                                                                                                                                                                                                                                             );

                                                                                                                                                                                                                                                                             }


                                                                                                                                                                                                                                                                             function mensagemContato() {

                                                                                                                                                                                                                                                                                 let nome = prompt("Digite seu nome:");

                                                                                                                                                                                                                                                                                     if (nome && nome.trim() !== "") {

                                                                                                                                                                                                                                                                                             alert(
                                                                                                                                                                                                                                                                                                         "Obrigada pela visita, " +
                                                                                                                                                                                                                                                                                                                     nome +
                                                                                                                                                                                                                                                                                                                                 "! 💜"
                                                                                                                                                                                                                                                                                                                                         );

                                                                                                                                                                                                                                                                                                                                             } else {

                                                                                                                                                                                                                                                                                                                                                     alert(
                                                                                                                                                                                                                                                                                                                                                                 "Obrigada por visitar o Blog da Francisca Allany! 💜"
                                                                                                                                                                                                                                                                                                                                                                         );

                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                             }.mensagem-foto {
                                                                                                                                                                                                                                                                                                                                                                                    position: fixed;
                                                                                                                                                                                                                                                                                                                                                                                        inset: 0;

                                                                                                                                                                                                                                                                                                                                                                                            background: rgba(0, 0, 0, 0.7);

                                                                                                                                                                                                                                                                                                                                                                                                display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                    justify-content: center;
                                                                                                                                                                                                                                                                                                                                                                                                        align-items: center;

                                                                                                                                                                                                                                                                                                                                                                                                            z-index: 9999;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                            .caixa-foto {
                                                                                                                                                                                                                                                                                                                                                                                                                background: white;
                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 25px;

                                                                                                                                                                                                                                                                                                                                                                                                                        width: 90%;
                                                                                                                                                                                                                                                                                                                                                                                                                            max-width: 400px;

                                                                                                                                                                                                                                                                                                                                                                                                                                text-align: center;

                                                                                                                                                                                                                                                                                                                                                                                                                                    border-radius: 20px;

                                                                                                                                                                                                                                                                                                                                                                                                                                        box-shadow: 0 10px 40px rgba(0, 0, 0, 0.3);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        .caixa-foto img {
                                                                                                                                                                                                                                                                                                                                                                                                                                            width: 180px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                height: 180px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                    object-fit: cover;

                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 50%;

                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin: 0 auto 20px;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: 5px solid #7657e8;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                .caixa-foto h2 {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: #7657e8;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin-bottom: 10px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .caixa-foto p {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: #666;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                margin-bottom: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }Blog_Francisca_Allany/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ├── index.html
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ├── style.css
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ├── script.js
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                │
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                └── img/
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    └── francisca.jpg
                                                                                                                                                                                                                                                                                                                                                                             }
}
}