// Array para armazenar os produtos do estoque
let estoque = [];

// 1. Cadastrar um novo produto
function cadastrarProduto(codigo, descricao, quantidade, valor) {

    // Verifica se o código já existe
        let existe = estoque.find(p => p.codigo === codigo);

            if (existe) {
                    console.log(`Erro: Já existe um produto com o código ${codigo}.`);
                            return;
                                }

                                    // Cria o objeto do produto
                                        let novoProduto = {
                                                codigo: codigo,
                                                        descricao: descricao,
                                                                quantidade: parseInt(quantidade),
                                                                        valor: parseFloat(valor)
                                                                            };

                                                                                // Adiciona o produto ao estoque
                                                                                    estoque.push(novoProduto);

                                                                                        console.log(`Produto "${descricao}" cadastrado com sucesso!`);
                                                                                        }

                                                                                        // 2. Listar os produtos
                                                                                        function listarProdutos() {

                                                                                            if (estoque.length === 0) {
                                                                                                    console.log("O estoque está vazio.");
                                                                                                            return;
                                                                                                                }

                                                                                                                    console.log("\n--- LISTA DE PRODUTOS NO ESTOQUE ---");

                                                                                                                        estoque.forEach(produto => {
                                                                                                                                console.log(
                                                                                                                                            `Código: ${produto.codigo} | ` +
                                                                                                                                                        `Descrição: ${produto.descricao} | ` +
                                                                                                                                                                    `Qtd: ${produto.quantidade} | ` +
                                                                                                                                                                                `Valor: R$ ${produto.valor.toFixed(2)}`
                                                                                                                                                                                        );
                                                                                                                                                                                            });

                                                                                                                                                                                                console.log("------------------------------------\n");
                                                                                                                                                                                                }

                                                                                                                                                                                                // 3. Alterar o valor de um produto
                                                                                                                                                                                                function alterarValor(codigo, novoValor) {

                                                                                                                                                                                                    let produto = estoque.find(p => p.codigo === codigo);

                                                                                                                                                                                                        if (produto) {

                                                                                                                                                                                                                produto.valor = parseFloat(novoValor);

                                                                                                                                                                                                                        console.log(
                                                                                                                                                                                                                                    `Valor do produto código ${codigo} alterado para R$ ${produto.valor.toFixed(2)}.`
                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                } else {

                                                                                                                                                                                                                                                        console.log(
                                                                                                                                                                                                                                                                    `Erro: Produto com o código ${codigo} não encontrado.`
                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                // 4. Alterar a quantidade de um produto
                                                                                                                                                                                                                                                                                function alterarQuantidade(codigo, novaQuantidade) {

                                                                                                                                                                                                                                                                                    let produto = estoque.find(p => p.codigo === codigo);

                                                                                                                                                                                                                                                                                        if (produto) {

                                                                                                                                                                                                                                                                                                produto.quantidade = parseInt(novaQuantidade);

                                                                                                                                                                                                                                                                                                        console.log(
                                                                                                                                                                                                                                                                                                                    `Quantidade do produto código ${codigo} alterada para ${produto.quantidade} unidades.`
                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                } else {

                                                                                                                                                                                                                                                                                                                                        console.log(
                                                                                                                                                                                                                                                                                                                                                    `Erro: Produto com o código ${codigo} não encontrado.`
                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                // 5. Menu principal
                                                                                                                                                                                                                                                                                                                                                                function iniciarMenu() {

                                                                                                                                                                                                                                                                                                                                                                    let continuar = true;

                                                                                                                                                                                                                                                                                                                                                                        while (continuar) {

                                                                                                                                                                                                                                                                                                                                                                                let opcao = prompt(
                                                                                                                                                                                                                                                                                                                                                                                            "=== SISTEMA DE ESTOQUE ===\n\n" +
                                                                                                                                                                                                                                                                                                                                                                                                        "1 - Cadastrar novo produto\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                    "2 - Listar produtos\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                "3 - Alterar valor\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                            "4 - Alterar quantidade\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "5 - Sair\n\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Digite uma opção:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    switch (opcao) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Cadastrar produto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "1":

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let cod = prompt("Digite o código do produto:");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let desc = prompt("Digite a descrição:");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let qtd = prompt("Digite a quantidade inicial:");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let val = prompt("Digite o valor unitário:");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cadastrarProduto(cod, desc, qtd, val);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Listar produtos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case "2":

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    listarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Alterar valor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "3":

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let codVal = prompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Digite o código do produto:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let novoVal = prompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Digite o novo valor:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alterarValor(codVal, novoVal);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Alterar quantidade
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "4":

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let codQtd = prompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Digite o código do produto:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let novaQtd = prompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Digite a nova quantidade:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alterarQuantidade(codQtd, novaQtd);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Sair
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case "5":

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            continuar = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log("Sistema encerrado.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Opção inválida
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    default:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert("Opção inválida!");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }