const nomeProduto = document.getElementById("nomeProduto");
const quantidadeProduto = document.getElementById("quantidadeProduto");
const precoProduto = document.getElementById("precoProduto");

const botaoAdicionar = document.getElementById("botaoAdicionar");

const listaProdutos = document.getElementById("listaProdutos");

const totalProdutos = document.getElementById("totalProdutos");
const totalItens = document.getElementById("totalItens");
const valorEstoque = document.getElementById("valorEstoque");


// Carrega os produtos salvos no navegador
let produtos = JSON.parse(localStorage.getItem("produtos")) || [];


// Salvar estoque
function salvarProdutos() {

    localStorage.setItem(
            "produtos",
                    JSON.stringify(produtos)
                        );

                        }


                        // Formatar dinheiro
                        function formatarDinheiro(valor) {

                            return valor.toLocaleString(
                                    "pt-BR",
                                            {
                                                        style: "currency",
                                                                    currency: "BRL"
                                                                            }
                                                                                );

                                                                                }


                                                                                // Mostrar produtos
                                                                                function mostrarProdutos() {

                                                                                    listaProdutos.innerHTML = "";

                                                                                        produtos.forEach(function(produto, indice) {

                                                                                                const linha = document.createElement("tr");


                                                                                                        // Nome
                                                                                                                const colunaNome = document.createElement("td");

                                                                                                                        colunaNome.textContent = produto.nome;


                                                                                                                                // Quantidade
                                                                                                                                        const colunaQuantidade = document.createElement("td");

                                                                                                                                                colunaQuantidade.textContent = produto.quantidade;

                                                                                                                                                        if (produto.quantidade === 0) {

                                                                                                                                                                    colunaQuantidade.textContent = "SEM ESTOQUE";

                                                                                                                                                                                colunaQuantidade.classList.add("semEstoque");

                                                                                                                                                                                        }


                                                                                                                                                                                                // Preço
                                                                                                                                                                                                        const colunaPreco = document.createElement("td");

                                                                                                                                                                                                                colunaPreco.textContent =
                                                                                                                                                                                                                            formatarDinheiro(produto.preco);


                                                                                                                                                                                                                                    // Total
                                                                                                                                                                                                                                            const colunaTotal = document.createElement("td");

                                                                                                                                                                                                                                                    const total =
                                                                                                                                                                                                                                                                produto.quantidade * produto.preco;

                                                                                                                                                                                                                                                                        colunaTotal.textContent =
                                                                                                                                                                                                                                                                                    formatarDinheiro(total);


                                                                                                                                                                                                                                                                                            // Ações
                                                                                                                                                                                                                                                                                                    const colunaAcoes = document.createElement("td");


                                                                                                                                                                                                                                                                                                            // Botão +
                                                                                                                                                                                                                                                                                                                    const botaoMais = document.createElement("button");

                                                                                                                                                                                                                                                                                                                            botaoMais.textContent = "+";

                                                                                                                                                                                                                                                                                                                                    botaoMais.classList.add("botaoMais");

                                                                                                                                                                                                                                                                                                                                            botaoMais.addEventListener("click", function() {

                                                                                                                                                                                                                                                                                                                                                        produtos[indice].quantidade++;

                                                                                                                                                                                                                                                                                                                                                                    salvarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                mostrarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                        });


                                                                                                                                                                                                                                                                                                                                                                                                // Botão -
                                                                                                                                                                                                                                                                                                                                                                                                        const botaoMenos = document.createElement("button");

                                                                                                                                                                                                                                                                                                                                                                                                                botaoMenos.textContent = "-";

                                                                                                                                                                                                                                                                                                                                                                                                                        botaoMenos.classList.add("botaoMenos");

                                                                                                                                                                                                                                                                                                                                                                                                                                botaoMenos.addEventListener("click", function() {

                                                                                                                                                                                                                                                                                                                                                                                                                                            if (produtos[indice].quantidade > 0) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                            produtos[indice].quantidade--;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    salvarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mostrarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Botão excluir
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const botaoExcluir = document.createElement("button");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                botaoExcluir.textContent = "Excluir";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        botaoExcluir.classList.add("botaoExcluir");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                botaoExcluir.addEventListener("click", function() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const confirmar = confirm(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Deseja excluir este produto?"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (confirmar) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    produtos.splice(indice, 1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    salvarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mostrarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                colunaAcoes.appendChild(botaoMais);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        colunaAcoes.appendChild(botaoMenos);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                colunaAcoes.appendChild(botaoExcluir);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        linha.appendChild(colunaNome);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                linha.appendChild(colunaQuantidade);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        linha.appendChild(colunaPreco);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                linha.appendChild(colunaTotal);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        linha.appendChild(colunaAcoes);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listaProdutos.appendChild(linha);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        atualizarResumo();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Adicionar produto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function adicionarProduto() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const nome = nomeProduto.value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const quantidade =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Number(quantidadeProduto.value);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const preco =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Number(precoProduto.value);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nome === "" ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        quantidadeProduto.value === "" ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                precoProduto.value === ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Preencha todos os campos!");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (quantidade < 0 || preco < 0) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Quantidade e preço não podem ser negativos!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const novoProduto = {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nome: nome,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        quantidade: quantidade,

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                preco: preco

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        produtos.push(novoProduto);


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            salvarProdutos();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mostrarProdutos();


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Limpar campos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nomeProduto.value = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quantidadeProduto.value = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                precoProduto.value = "";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    nomeProduto.focus();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Resumo do estoque
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function atualizarResumo() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalProdutos.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                produtos.length;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let quantidadeTotal = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let valorTotal = 0;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            produtos.forEach(function(produto) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    quantidadeTotal +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                produto.quantidade;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        valorTotal +=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    produto.quantidade *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                produto.preco;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalItens.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                quantidadeTotal;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    valorEstoque.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            formatarDinheiro(valorTotal);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Clique para adicionar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            botaoAdicionar.addEventListener(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "click",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    adicionarProduto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Enter para adicionar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.addEventListener(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "keypress",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function(evento) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (evento.key === "Enter") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                adicionarProduto();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Mostrar estoque quando abrir o site
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarProdutos();