<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Minha Página Web</title>

                <style>
                        body {
                                    font-family: Arial, sans-serif;
                                                margin: 0;
                                                            padding: 0;
                                                                        background-color: #f4f4f4;
                                                                                    text-align: center;
                                                                                            }

                                                                                                    header {
                                                                                                                background-color: #4CAF50;
                                                                                                                            color: white;
                                                                                                                                        padding: 20px;
                                                                                                                                                }

                                                                                                                                                        main {
                                                                                                                                                                    padding: 30px;
                                                                                                                                                                            }

                                                                                                                                                                                    button {
                                                                                                                                                                                                background-color: #4CAF50;
                                                                                                                                                                                                            color: white;
                                                                                                                                                                                                                        border: none;
                                                                                                                                                                                                                                    padding: 12px 20px;
                                                                                                                                                                                                                                                font-size: 16px;
                                                                                                                                                                                                                                                            border-radius: 8px;
                                                                                                                                                                                                                                                                        cursor: pointer;
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                        button:hover {
                                                                                                                                                                                                                                                                                                    background-color: #45a049;
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                    footer {
                                                                                                                                                                                                                                                                                                                                background-color: #333;
                                                                                                                                                                                                                                                                                                                                            color: white;
                                                                                                                                                                                                                                                                                                                                                        padding: 10px;
                                                                                                                                                                                                                                                                                                                                                                    position: fixed;
                                                                                                                                                                                                                                                                                                                                                                                width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                            bottom: 0;
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                                                                                                                                        <body>

                                                                                                                                                                                                                                                                                                                                                                                                            <header>
                                                                                                                                                                                                                                                                                                                                                                                                                    <h1>Bem-vindo ao Meu Site</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                        </header>

                                                                                                                                                                                                                                                                                                                                                                                                                            <main>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2>Página Principal</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Esta página usa HTML, CSS e JavaScript.</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onclick="mostrarMensagem()">Clique aqui</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p id="mensagem"></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>© 2026 Meu Site</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </footer>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function mostrarMensagem() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("mensagem").innerHTML = "Você clicou no botão com sucesso!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>