// Array que armazena as tarefas
let tarefas = [];

// Código da próxima tarefa
let proximoCodigo = 1;

// Elementos do HTML
const formulario = document.getElementById("formTarefa");
const campoTitulo = document.getElementById("titulo");
const campoPrioridade = document.getElementById("prioridade");
const listaTarefas = document.getElementById("listaTarefas");
const mensagem = document.getElementById("mensagem");

// Cadastro de uma nova tarefa
formulario.addEventListener("submit", function(event) {
    event.preventDefault();

        const titulo = campoTitulo.value.trim();
            const prioridade = Number(campoPrioridade.value);

                // Validação do título
                    if (titulo.length < 5) {
                            mostrarMensagem(
                                        "O título deve ter no mínimo 5 caracteres.",
                                                    "erro"
                                                            );
                                                                    return;
                                                                        }

                                                                            // Validação da prioridade
                                                                                if (![1, 2, 3].includes(prioridade)) {
                                                                                        mostrarMensagem(
                                                                                                    "A prioridade deve ser 1, 2 ou 3.",
                                                                                                                "erro"
                                                                                                                        );
                                                                                                                                return;
                                                                                                                                    }

                                                                                                                                        // Criação da tarefa
                                                                                                                                            const tarefa = {
                                                                                                                                                    codigo: proximoCodigo,
                                                                                                                                                            titulo: titulo,
                                                                                                                                                                    prioridade: prioridade,
                                                                                                                                                                            concluida: false
                                                                                                                                                                                };

                                                                                                                                                                                    tarefas.push(tarefa);
                                                                                                                                                                                        proximoCodigo++;

                                                                                                                                                                                            mostrarMensagem("Tarefa cadastrada com sucesso!", "sucesso");

                                                                                                                                                                                                formulario.reset();

                                                                                                                                                                                                    campoPrioridade.value = "2";

                                                                                                                                                                                                        listarTarefas();
                                                                                                                                                                                                        });

                                                                                                                                                                                                        // Retorna o nome da prioridade
                                                                                                                                                                                                        function nomePrioridade(prioridade) {
                                                                                                                                                                                                            switch (prioridade) {
                                                                                                                                                                                                                    case 1:
                                                                                                                                                                                                                                return "Alta";
                                                                                                                                                                                                                                        case 2:
                                                                                                                                                                                                                                                    return "Média";
                                                                                                                                                                                                                                                            case 3:
                                                                                                                                                                                                                                                                        return "Baixa";
                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                            return "Inválida";
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                // Lista todas as tarefas cadastradas
                                                                                                                                                                                                                                                                                                function listarTarefas() {
                                                                                                                                                                                                                                                                                                    listaTarefas.innerHTML = "";

                                                                                                                                                                                                                                                                                                        if (tarefas.length === 0) {
                                                                                                                                                                                                                                                                                                                listaTarefas.innerHTML =
                                                                                                                                                                                                                                                                                                                            '<p class="vazio">Nenhuma tarefa cadastrada.</p>';
                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            tarefas.forEach(function(tarefa) {
                                                                                                                                                                                                                                                                                                                                                    const elemento = document.createElement("div");

                                                                                                                                                                                                                                                                                                                                                            elemento.className = "tarefa";

                                                                                                                                                                                                                                                                                                                                                                    if (tarefa.concluida) {
                                                                                                                                                                                                                                                                                                                                                                                elemento.classList.add("concluida");
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                const titulo = document.createElement("h3");
                                                                                                                                                                                                                                                                                                                                                                                                        titulo.textContent = tarefa.titulo;

                                                                                                                                                                                                                                                                                                                                                                                                                const codigo = document.createElement("p");
                                                                                                                                                                                                                                                                                                                                                                                                                        codigo.textContent = "Código: " + tarefa.codigo;

                                                                                                                                                                                                                                                                                                                                                                                                                                const prioridade = document.createElement("p");
                                                                                                                                                                                                                                                                                                                                                                                                                                        prioridade.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Prioridade: " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                tarefa.prioridade +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " - " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nomePrioridade(tarefa.prioridade);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const status = document.createElement("p");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Status: " +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (tarefa.concluida ? "Concluída" : "Pendente");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const acoes = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                acoes.className = "acoes";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Botão para concluir a tarefa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const botaoConcluir = document.createElement("button");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        botaoConcluir.className = "concluir";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                botaoConcluir.textContent = tarefa.concluida
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "Concluída"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : "Marcar como concluída";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                botaoConcluir.disabled = tarefa.concluida;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        botaoConcluir.addEventListener("click", function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    concluirTarefa(tarefa.codigo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Botão para alterar a prioridade
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const botaoAlterar = document.createElement("button");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    botaoAlterar.className = "alterar";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            botaoAlterar.textContent = "Alterar prioridade";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    botaoAlterar.addEventListener("click", function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alterarPrioridade(tarefa.codigo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                acoes.appendChild(botaoConcluir);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        acoes.appendChild(botaoAlterar);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elemento.appendChild(titulo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elemento.appendChild(codigo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elemento.appendChild(prioridade);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elemento.appendChild(status);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elemento.appendChild(acoes);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        listaTarefas.appendChild(elemento);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Marca uma tarefa como concluída
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function concluirTarefa(codigo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const tarefa = tarefas.find(function(item) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return item.codigo === codigo;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (tarefa) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tarefa.concluida = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mostrarMensagem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Tarefa marcada como concluída!",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "sucesso"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        listarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Altera a prioridade de uma tarefa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function alterarPrioridade(codigo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const tarefa = tarefas.find(function(item) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return item.codigo === codigo;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!tarefa) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarMensagem("Tarefa não encontrada.", "erro");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const novaPrioridade = prompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Digite a nova prioridade:\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "1 - Alta\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "2 - Média\n" +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "3 - Baixa"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Permite cancelar sem alterar a tarefa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (novaPrioridade === null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const prioridade = Number(novaPrioridade);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                !["1", "2", "3"].includes(novaPrioridade.trim())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarMensagem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Prioridade inválida! Digite 1, 2 ou 3.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "erro"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tarefa.prioridade = prioridade;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mostrarMensagem(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Prioridade alterada com sucesso!",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "sucesso"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        listarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Exibe mensagens para o usuário
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function mostrarMensagem(texto, tipo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mensagem.textContent = texto;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mensagem.className = tipo;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Exibe a lista inicial
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();