!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Super Quiz Kids</title>

        <style>
            * {
                  box-sizing: border-box;
                        font-family: Arial, sans-serif;
                            }

                                body {
                                      margin: 0;
                                            min-height: 100vh;
                                                  background: linear-gradient(135deg, #8ec5fc, #e0c3fc);
                                                        display: flex;
                                                              justify-content: center;
                                                                    align-items: center;
                                                                        }

                                                                            .app {
                                                                                  width: 95%;
                                                                                        max-width: 430px;
                                                                                              background: white;
                                                                                                    border-radius: 25px;
                                                                                                          padding: 25px;
                                                                                                                text-align: center;
                                                                                                                      box-shadow: 0 8px 25px rgba(0,0,0,0.2);
                                                                                                                          }

                                                                                                                              h1 {
                                                                                                                                    color: #6c4bc1;
                                                                                                                                          margin-bottom: 5px;
                                                                                                                                              }

                                                                                                                                                  .emoji {
                                                                                                                                                        font-size: 60px;
                                                                                                                                                            }

                                                                                                                                                                .score {
                                                                                                                                                                      background: #f1edff;
                                                                                                                                                                            padding: 10px;
                                                                                                                                                                                  border-radius: 15px;
                                                                                                                                                                                        margin: 15px 0;
                                                                                                                                                                                              font-weight: bold;
                                                                                                                                                                                                    color: #5737a4;
                                                                                                                                                                                                        }

                                                                                                                                                                                                            #question {
                                                                                                                                                                                                                  font-size: 21px;
                                                                                                                                                                                                                        font-weight: bold;
                                                                                                                                                                                                                              margin: 25px 0;
                                                                                                                                                                                                                                    color: #333;
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                            .answers {
                                                                                                                                                                                                                                                  display: grid;
                                                                                                                                                                                                                                                        gap: 12px;
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                button {
                                                                                                                                                                                                                                                                      border: none;
                                                                                                                                                                                                                                                                            border-radius: 15px;
                                                                                                                                                                                                                                                                                  padding: 15px;
                                                                                                                                                                                                                                                                                        font-size: 17px;
                                                                                                                                                                                                                                                                                              font-weight: bold;
                                                                                                                                                                                                                                                                                                    cursor: pointer;
                                                                                                                                                                                                                                                                                                          background: #eee8ff;
                                                                                                                                                                                                                                                                                                                color: #4d328d;
                                                                                                                                                                                                                                                                                                                      transition: 0.2s;
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                              button:hover {
                                                                                                                                                                                                                                                                                                                                    transform: scale(1.03);
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            button.correct {
                                                                                                                                                                                                                                                                                                                                                  background: #9be7a8;
                                                                                                                                                                                                                                                                                                                                                        color: #155b20;
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                button.wrong {
                                                                                                                                                                                                                                                                                                                                                                      background: #ffaaaa;
                                                                                                                                                                                                                                                                                                                                                                            color: #8a1f1f;
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                    #next {
                                                                                                                                                                                                                                                                                                                                                                                          margin-top: 20px;
                                                                                                                                                                                                                                                                                                                                                                                                background: #6c4bc1;
                                                                                                                                                                                                                                                                                                                                                                                                      color: white;
                                                                                                                                                                                                                                                                                                                                                                                                            display: none;
                                                                                                                                                                                                                                                                                                                                                                                                                  width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                          #message {
                                                                                                                                                                                                                                                                                                                                                                                                                                min-height: 25px;
                                                                                                                                                                                                                                                                                                                                                                                                                                      font-weight: bold;
                                                                                                                                                                                                                                                                                                                                                                                                                                            margin-top: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    .restart {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: #ffca5c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: #684800;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 100%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin-top: 15px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </head>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <body>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="app">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="emoji">🧸🎮</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h1>Super Quiz Kids</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Aprenda brincando!</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="score">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ⭐ Pontos: <span id="score">0</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div id="question"></div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="answers" id="answers"></div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div id="message"></div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button id="next" onclick="nextQuestion()">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Próxima pergunta ➡️
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button class="restart" onclick="restartGame()">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  🔄 Reiniciar jogo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const questions = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "Quanto é 2 + 3?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answers: ["4", "5", "6", "7"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      correct: "5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "Qual animal faz 'miau'? 🐱",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answers: ["Cachorro", "Gato", "Vaca", "Cavalo"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      correct: "Gato"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "Qual é a primeira letra do alfabeto?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answers: ["A", "B", "C", "D"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      correct: "A"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "Quantos dias existem em uma semana?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answers: ["5", "6", "7", "8"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      correct: "7"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "Qual planeta é conhecido como Planeta Vermelho? 🔴",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answers: ["Terra", "Marte", "Júpiter", "Saturno"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      correct: "Marte"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              question: "Quanto é 5 × 2?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answers: ["7", "8", "10", "12"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      correct: "10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let currentQuestion = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let score = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        