// Array que vai armazenar as tarefas
let tarefas = [];


// Cadastrar uma nova tarefa
function cadastrarTarefa() {

    let codigo = document.getElementById("codigo").value;
        let titulo = document.getElementById("titulo").value;
            let prioridade = Number(
                    document.getElementById("prioridade").value
                        );

                            // Verifica se o código foi preenchido
                                if (codigo === "") {
                                        alert("Digite o código da tarefa!");
                                                return;
                                                    }

                                                        // Verifica se o título possui pelo menos 5 caracteres
                                                            if (titulo.length < 5) {
                                                                    alert("O título deve ter no mínimo 5 caracteres!");
                                                                            return;
                                                                                }

                                                                                    // Verifica se a prioridade está entre 1 e 3
                                                                                        if (prioridade < 1 || prioridade > 3) {
                                                                                                alert("A prioridade deve ser entre 1 e 3!");
                                                                                                        return;
                                                                                                            }

                                                                                                                // Verifica se o código já existe
                                                                                                                    let codigoExiste = tarefas.some(
                                                                                                                            tarefa => tarefa.codigo == codigo
                                                                                                                                );

                                                                                                                                    if (codigoExiste) {
                                                                                                                                            alert("Esse código já está cadastrado!");
                                                                                                                                                    return;
                                                                                                                                                        }

                                                                                                                                                            // Cria a tarefa
                                                                                                                                                                let novaTarefa = {
                                                                                                                                                                        codigo: codigo,
                                                                                                                                                                                titulo: titulo,
                                                                                                                                                                                        prioridade: prioridade,
                                                                                                                                                                                                concluida: false
                                                                                                                                                                                                    };

                                                                                                                                                                                                        // Adiciona ao array
                                                                                                                                                                                                            tarefas.push(novaTarefa);

                                                                                                                                                                                                                // Limpa os campos
                                                                                                                                                                                                                    document.getElementById("codigo").value = "";
                                                                                                                                                                                                                        document.getElementById("titulo").value = "";

                                                                                                                                                                                                                            // Atualiza a lista
                                                                                                                                                                                                                                listarTarefas();
                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                // Listar todas as tarefas
                                                                                                                                                                                                                                function listarTarefas() {

                                                                                                                                                                                                                                    let lista = document.getElementById("listaTarefas");

                                                                                                                                                                                                                                        lista.innerHTML = "";

                                                                                                                                                                                                                                            if (tarefas.length === 0) {
                                                                                                                                                                                                                                                    lista.innerHTML = "<p>Nenhuma tarefa cadastrada.</p>";
                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    tarefas.forEach((tarefa, indice) => {

                                                                                                                                                                                                                                                                            let div = document.createElement("div");

                                                                                                                                                                                                                                                                                    div.className = "tarefa";

                                                                                                                                                                                                                                                                                            if (tarefa.concluida) {
                                                                                                                                                                                                                                                                                                        div.classList.add("concluida");
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                        let textoPrioridade = "";

                                                                                                                                                                                                                                                                                                                                if (tarefa.prioridade === 1) {
                                                                                                                                                                                                                                                                                                                                            textoPrioridade = "Alta";
                                                                                                                                                                                                                                                                                                                                                    } else if (tarefa.prioridade === 2) {
                                                                                                                                                                                                                                                                                                                                                                textoPrioridade = "Média";
                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                    textoPrioridade = "Baixa";
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    div.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                <h3>${tarefa.titulo}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                            <p><strong>Código:</strong> ${tarefa.codigo}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <p class="prioridade">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Prioridade:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${tarefa.prioridade} - ${textoPrioridade}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>Status:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ${tarefa.concluida ? "Concluída" : "Pendente"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="acoes">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onclick="concluirTarefa(${indice})">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${tarefa.concluida ? "Desmarcar" : "Concluir"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onclick="alterarPrioridade(${indice})">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Alterar prioridade
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lista.appendChild(div);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Marcar tarefa como concluída
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function concluirTarefa(indice) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tarefas[indice].concluida =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            !tarefas[indice].concluida;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Alterar a prioridade
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function alterarPrioridade(indice) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let novaPrioridade = prompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Digite a nova prioridade (1 = Alta, 2 = Média, 3 = Baixa):"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    novaPrioridade = Number(novaPrioridade);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                novaPrioridade < 1 ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        novaPrioridade > 3 ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                isNaN(novaPrioridade)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Digite uma prioridade válida: 1, 2 ou 3.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tarefas[indice].prioridade = novaPrioridade;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Mostra a lista inicialmente
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();