// 📋 Banco de Perguntas
const perguntas = [
    {
            pergunta: "Qual é o jogo mais vendido de todos os tempos?",
                    opcoes: ["GTA V", "Minecraft", "Tetris", "Mario Kart 8"],
                            correta: 1
                                },
                                    {
                                            pergunta: "Em qual jogo o personagem é chamado de 'Link'?",
                                                    opcoes: ["Super Mario", "Zelda", "Pokémon", "Final Fantasy"],
                                                            correta: 1
                                                                },
                                                                    {
                                                                            pergunta: "Qual empresa criou o console PlayStation?",
                                                                                    opcoes: ["Microsoft", "Nintendo", "Sony", "Sega"],
                                                                                            correta: 2
                                                                                                },
                                                                                                    {
                                                                                                            pergunta: "Qual é o nome do encanador mais famoso dos games?",
                                                                                                                    opcoes: ["Luigi", "Mario", "Peach", "Bowser"],
                                                                                                                            correta: 1
                                                                                                                                },
                                                                                                                                    {
                                                                                                                                            pergunta: "Em que ano foi lançado o primeiro jogo da série GTA?",
                                                                                                                                                    opcoes: ["1997", "2001", "2005", "1999"],
                                                                                                                                                            correta: 0
                                                                                                                                                                }
                                                                                                                                                                ];

                                                                                                                                                                // 📊 Variáveis
                                                                                                                                                                let indiceAtual = 0;
                                                                                                                                                                let pontuacao = 0;
                                                                                                                                                                let tempoRestante = 20;
                                                                                                                                                                let cronometro;

                                                                                                                                                                // 🎯 Elementos
                                                                                                                                                                const telaInicio = document.getElementById('tela-inicio');
                                                                                                                                                                const telaJogo = document.getElementById('tela-jogo');
                                                                                                                                                                const telaFinal = document.getElementById('tela-final');
                                                                                                                                                                const elPergunta = document.getElementById('pergunta');
                                                                                                                                                                const elRespostas = document.getElementById('respostas');
                                                                                                                                                                const elPontos = document.getElementById('pontos');
                                                                                                                                                                const elTempo = document.getElementById('tempo');
                                                                                                                                                                const proxBtn = document.getElementById('prox-btn');
                                                                                                                                                                const elNotaFinal = document.getElementById('nota-final');
                                                                                                                                                                const elTotalPerguntas = document.getElementById('total-perguntas');
                                                                                                                                                                const elMensagemFinal = document.getElementById('mensagem-final');

                                                                                                                                                                // 🔄 Trocar Tela
                                                                                                                                                                function mostrarTela(nomeTela) {
                                                                                                                                                                    document.querySelectorAll('.tela').forEach(t => t.classList.remove('ativa'));
                                                                                                                                                                        document.getElementById(`tela-${nomeTela}`).classList.add('ativa');
                                                                                                                                                                        }

                                                                                                                                                                        // 🚀 Iniciar Jogo
                                                                                                                                                                        function iniciarJogo() {
                                                                                                                                                                            indiceAtual = 0;
                                                                                                                                                                                pontuacao = 0;
                                                                                                                                                                                    elPontos.textContent = pontuacao;
                                                                                                                                                                                        mostrarTela('jogo');
                                                                                                                                                                                            carregarPergunta();
                                                                                                                                                                                            }

                                                                                                                                                                                            // 📝 Carregar Pergunta
                                                                                                                                                                                            function carregarPergunta() {
                                                                                                                                                                                                proxBtn.style.display = 'none';
                                                                                                                                                                                                    const perguntaAtual = perguntas[indiceAtual];
                                                                                                                                                                                                        elPergunta.textContent = `${indiceAtual + 1}. ${perguntaAtual.pergunta}`;
                                                                                                                                                                                                            elRespostas.innerHTML = '';

                                                                                                                                                                                                                perguntaAtual.opcoes.forEach((opcao, i) => {
                                                                                                                                                                                                                        const div = document.createElement('div');
                                                                                                                                                                                                                                div.classList.add('opcao');
                                                                                                                                                                                                                                        div.textContent = opcao;
                                                                                                                                                                                                                                                div.onclick = () => verificarResposta(i, perguntaAtual.correta);
                                                                                                                                                                                                                                                        elRespostas.appendChild(div);
                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                iniciarCronometro();
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                // ⏱️ Cronômetro
                                                                                                                                                                                                                                                                function iniciarCronometro() {
                                                                                                                                                                                                                                                                    tempoRestante = 20;
                                                                                                                                                                                                                                                                        elTempo.textContent = tempoRestante;
                                                                                                                                                                                                                                                                            clearInterval(cronometro);
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    cronometro = setInterval(() => {
                                                                                                                                                                                                                                                                                            tempoRestante--;
                                                                                                                                                                                                                                                                                                    elTempo.textContent = tempoRestante;
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    if (tempoRestante <= 0) {
                                                                                                                                                                                                                                                                                                                                clearInterval(cronometro);
                                                                                                                                                                                                                                                                                                                                            desabilitarRespostas();
                                                                                                                                                                                                                                                                                                                                                        alert("⏰ Tempo esgotado!");
                                                                                                                                                                                                                                                                                                                                                                    proxBtn.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                }, 1000);
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                // ✅ Verificar Resposta
                                                                                                                                                                                                                                                                                                                                                                                function verificarResposta(escolhida, correta) {
                                                                                                                                                                                                                                                                                                                                                                                    clearInterval(cronometro);
                                                                                                                                                                                                                                                                                                                                                                                        desabilitarRespostas();
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                const opcoes = document.querySelectorAll('.opcao');
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        if (escolhida === correta) {
                                                                                                                                                                                                                                                                                                                                                                                                                opcoes[escolhida].classList.add('correta');
                                                                                                                                                                                                                                                                                                                                                                                                                        pontuacao += 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                elPontos.textContent = pontuacao;
                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            opcoes[escolhida].classList.add('errada');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    opcoes[correta].classList.add('correta');
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            proxBtn.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 🔒 Desabilitar Respostas
                                                                                                                                                                                                                                                                                                                                                                                                                                                            function desabilitarRespostas() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.querySelectorAll('.opcao').forEach(op => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        op.classList.add('selecionada');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ➡️ Próxima Pergunta
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function proximaPergunta() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                indiceAtual++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (indiceAtual < perguntas.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            carregarPergunta();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarResultado();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 🏆 Mostrar Resultado Final
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function mostrarResultado() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                clearInterval(cronometro);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mostrarTela('final');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elNotaFinal.textContent = pontuacao / 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elTotalPerguntas.textContent = perguntas.length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let mensagem = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const porcentagem = pontuacao / 10 / perguntas.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (porcentagem === 1) mensagem = "🎉 Perfeito! Você é um expert em jogos!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else if (porcentagem >= 0.7) mensagem = "👏 Muito bom! Conhece bem o assunto!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (porcentagem >= 0.5) mensagem = "🙂 Bom trabalho! Mas pode melhorar!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else mensagem = "💫 Não desista! Jogue novamente e melhore!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            elMensagemFinal.textContent = mensagem;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 🔁 Reiniciar Jogo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function reiniciarJogo() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mostrarTela('inicio');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                