
const questions = [
  {
      category: "FUTEBOL BRASILEIRO",
          question: "Qual seleção venceu a Copa do Mundo de 2002?",
              answers: [
                    "Argentina",
                          "Brasil",
                                "Alemanha",
                                      "França"
                                          ],
                                              correct: 1
                                                },
                                                  {
                                                      category: "HISTÓRIA DO FUTEBOL",
                                                          question: "Quantos jogadores cada time começa em campo no futebol tradicional?",
                                                              answers: [
                                                                    "9 jogadores",
                                                                          "10 jogadores",
                                                                                "11 jogadores",
                                                                                      "12 jogadores"
                                                                                          ],
                                                                                              correct: 2
                                                                                                },
                                                                                                  {
                                                                                                      category: "FUTEBOL INTERNACIONAL",
                                                                                                          question: "Qual país sediou a Copa do Mundo de 2018?",
                                                                                                              answers: [
                                                                                                                    "Brasil",
                                                                                                                          "Rússia",
                                                                                                                                "França",
                                                                                                                                      "Espanha"
                                                                                                                                          ],
                                                                                                                                              correct: 1
                                                                                                                                                },
                                                                                                                                                  {
                                                                                                                                                      category: "REGRAS DO FUTEBOL",
                                                                                                                                                          question: "Qual cartão significa expulsão de um jogador?",
                                                                                                                                                              answers: [
                                                                                                                                                                    "Cartão azul",
                                                                                                                                                                          "Cartão amarelo",
                                                                                                                                                                                "Cartão verde",
                                                                                                                                                                                      "Cartão vermelho"
                                                                                                                                                                                          ],
                                                                                                                                                                                              correct: 3
                                                                                                                                                                                                },
                                                                                                                                                                                                  {
                                                                                                                                                                                                      category: "COPA DO MUNDO",
                                                                                                                                                                                                          question: "Qual país conquistou a Copa do Mundo de 2014?",
                                                                                                                                                                                                              answers: [
                                                                                                                                                                                                                    "Brasil",
                                                                                                                                                                                                                          "Alemanha",
                                                                                                                                                                                                                                "Argentina",
                                                                                                                                                                                                                                      "Itália"
                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                              correct: 1
                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                      category: "FUTEBOL",
                                                                                                                                                                                                                                                          question: "Qual é a duração regulamentar de uma partida de futebol?",
                                                                                                                                                                                                                                                              answers: [
                                                                                                                                                                                                                                                                    "60 minutos",
                                                                                                                                                                                                                                                                          "70 minutos",
                                                                                                                                                                                                                                                                                "80 minutos",
                                                                                                                                                                                                                                                                                      "90 minutos"
                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                              correct: 3
                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                      category: "FUTEBOL BRASILEIRO",
                                                                                                                                                                                                                                                                                                          question: "Qual clube é conhecido como Timão?",
                                                                                                                                                                                                                                                                                                              answers: [
                                                                                                                                                                                                                                                                                                                    "Corinthians",
                                                                                                                                                                                                                                                                                                                          "Palmeiras",
                                                                                                                                                                                                                                                                                                                                "Flamengo",
                                                                                                                                                                                                                                                                                                                                      "Santos"
                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                              correct: 0
                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                      category: "FUTEBOL INTERNACIONAL",
                                                                                                                                                                                                                                                                                                                                                          question: "Qual país é conhecido pela seleção chamada La Albiceleste?",
                                                                                                                                                                                                                                                                                                                                                              answers: [
                                                                                                                                                                                                                                                                                                                                                                    "Uruguai",
                                                                                                                                                                                                                                                                                                                                                                          "Chile",
                                                                                                                                                                                                                                                                                                                                                                                "Argentina",
                                                                                                                                                                                                                                                                                                                                                                                      "Colômbia"
                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                              correct: 2
                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                      category: "REGRAS DO FUTEBOL",
                                                                                                                                                                                                                                                                                                                                                                                                          question: "Qual é a função principal do goleiro?",
                                                                                                                                                                                                                                                                                                                                                                                                              answers: [
                                                                                                                                                                                                                                                                                                                                                                                                                    "Marcar todos os gols",
                                                                                                                                                                                                                                                                                                                                                                                                                          "Defender a própria baliza",
                                                                                                                                                                                                                                                                                                                                                                                                                                "Cobrar todos os escanteios",
                                                                                                                                                                                                                                                                                                                                                                                                                                      "Atuar sempre no ataque"
                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                              correct: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      category: "COPA DO MUNDO",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          question: "Qual país venceu a Copa do Mundo de 2022?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              answers: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "França",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Brasil",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Argentina",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Croácia"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              correct: 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let currentQuestion = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let score = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let answered = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const questionEl = document.getElementById("question");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const answersEl = document.getElementById("answers");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const categoryEl = document.getElementById("category");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const feedbackEl = document.getElementById("feedback");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const nextBtn = document.getElementById("nextBtn");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const scoreEl = document.getElementById("score");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const currentEl = document.getElementById("current");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const totalEl = document.getElementById("total");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const progressEl = document.getElementById("progress");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const quizEl = document.getElementById("quiz");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const resultEl = document.getElementById("result");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const finalScoreEl = document.getElementById("finalScore");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const resultMessageEl = document.getElementById("resultMessage");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const restartBtn = document.getElementById("restartBtn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                totalEl.textContent = questions.length;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function loadQuestion() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  answered = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const question = questions[currentQuestion];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      categoryEl.textContent = question.category;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        questionEl.textContent = question.question;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          currentEl.textContent = currentQuestion + 1;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            progressEl.style.width =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `${(currentQuestion / questions.length) * 100}%`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  feedbackEl.textContent = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    feedbackEl.className = "feedback";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nextBtn.disabled = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        answersEl.innerHTML = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          question.answers.forEach((answer, index) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const button = document.createElement("button");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  button.className = "answer";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      button.textContent = `${String.fromCharCode(65 + index)}. ${answer}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          button.addEventListener("click", () => checkAnswer(index));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              answersEl.appendChild(button);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function checkAnswer(selectedIndex) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (answered) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    answered = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const question = questions[currentQuestion];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const buttons = document.querySelectorAll(".answer");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          buttons.forEach(button => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              button.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (selectedIndex === question.correct) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      score += 10;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          scoreEl.textContent = score;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              buttons[selectedIndex].classList.add("correct");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  feedbackEl.textContent = "✅ Resposta correta! +10 pontos";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      feedbackEl.className = "feedback correct-text";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            buttons[selectedIndex].classList.add("wrong");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                buttons[question.correct].classList.add("correct");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    feedbackEl.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `❌ Resposta incorreta! A correta era: ${question.answers[question.correct]}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              feedbackEl.className = "feedback wrong-text";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  nextBtn.disabled = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (currentQuestion === questions.length - 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nextBtn.textContent = "Ver resultado 🏆";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nextBtn.textContent = "Próxima pergunta ➜";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!answered) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    currentQuestion++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (currentQuestion >= questions.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          showResult();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loadQuestion();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function showResult() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    quizEl.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resultEl.classList.remove("hidden");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        progressEl.style.width = "100%";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          finalScoreEl.textContent = score;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const percentage = (score / (questions.length * 10)) * 100;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (percentage === 100) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  resultMessageEl.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "🏆 Perfeito! Você acertou todas as perguntas!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else if (percentage >= 70) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              resultMessageEl.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "🔥 Excelente! Você entende muito de futebol!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else if (percentage >= 50) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          resultMessageEl.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "👏 Bom trabalho! Continue treinando seus conhecimentos!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resultMessageEl.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "⚽ Continue praticando! O próximo desafio pode ser ainda melhor!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              restartBtn.addEventListener("click", () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currentQuestion = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  score = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scoreEl.textContent = score;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resultEl.classList.add("hidden");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        quizEl.classList.remove("hidden");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          nextBtn.textContent = "Próxima pergunta ➜";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loadQuestion();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loadQuestion();