
// Seletores do DOM com segurança garantida
const taskForm = document.getElementById('taskForm');
const taskTitleInput = document.getElementById('taskTitle');
const taskCategorySelect = document.getElementById('taskCategory');
const taskPrioritySelect = document.getElementById('taskPriority');
const taskDateInput = document.getElementById('taskDate');
const tasksList = document.getElementById('tasksList');
const emptyState = document.getElementById('emptyState');
const searchInput = document.getElementById('searchInput');
const filterBtns = document.querySelectorAll('.filter-btn');

const statTotal = document.getElementById('statTotal');
const statPending = document.getElementById('statPending');
const statCompleted = document.getElementById('statCompleted');

// Estado da Aplicação
let tasks = JSON.parse(localStorage.getItem('taskmatrix_tasks')) || [];
let currentFilter = 'all';
let currentSearchTerm = '';

// Inicializar Aplicativo
function init() {
    renderTasks();
        setupEventListeners();
        }

        // Configurar Ouvintes de Eventos
        function setupEventListeners() {
            if (taskForm) {
                    taskForm.addEventListener('submit', (e) => {
                                e.preventDefault();
                                            createNewTask();
                                                    });
                                                        }

                                                            if (searchInput) {
                                                                    searchInput.addEventListener('input', (e) => {
                                                                                currentSearchTerm = e.target.value.toLowerCase();
                                                                                            renderTasks();
                                                                                                    });
                                                                                                        }

                                                                                                            filterBtns.forEach(btn => {
                                                                                                                    btn.addEventListener('click', () => {
                                                                                                                                filterBtns.forEach(b => b.classList.remove('active'));
                                                                                                                                            btn.classList.add('active');
                                                                                                                                                        currentFilter = btn.getAttribute('data-filter');
                                                                                                                                                                    renderTasks();
                                                                                                                                                                            });
                                                                                                                                                                                });
                                                                                                                                                                                }

                                                                                                                                                                                // Criar Nova Tarefa
                                                                                                                                                                                function createNewTask() {
                                                                                                                                                                                    const title = taskTitleInput.value.trim();
                                                                                                                                                                                        if (!title) return;

                                                                                                                                                                                            const newTask = {
                                                                                                                                                                                                    id: Date.now().toString(),
                                                                                                                                                                                                            title: title,
                                                                                                                                                                                                                    category: taskCategorySelect.value,
                                                                                                                                                                                                                            priority: taskPrioritySelect.value,
                                                                                                                                                                                                                                    date: taskDateInput.value || 'Sem prazo',
                                                                                                                                                                                                                                            completed: false
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                    tasks.unshift(newTask);
                                                                                                                                                                                                                                                        saveAndRender();
                                                                                                                                                                                                                                                            taskForm.reset();
                                                                                                                                                                                                                                                                taskPrioritySelect.value = 'media'; // Valor padrão
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                // Alternar Status de Conclusão
                                                                                                                                                                                                                                                                function toggleTask(id) {
                                                                                                                                                                                                                                                                    tasks = tasks.map(task => {
                                                                                                                                                                                                                                                                            if (task.id === id) {
                                                                                                                                                                                                                                                                                        return { ...task, completed: !task.completed };
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                        return task;
                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                saveAndRender();
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                // Deletar Tarefa
                                                                                                                                                                                                                                                                                                                function deleteTask(id) {
                                                                                                                                                                                                                                                                                                                    tasks = tasks.filter(task => task.id !== id);
                                                                                                                                                                                                                                                                                                                        saveAndRender();
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                        // Salvar no LocalStorage e Atualizar Interface
                                                                                                                                                                                                                                                                                                                        function saveAndRender() {
                                                                                                                                                                                                                                                                                                                            localStorage.setItem('taskmatrix_tasks', JSON.stringify(tasks));
                                                                                                                                                                                                                                                                                                                                renderTasks();
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                // Atualizar Estatísticas do Painel
                                                                                                                                                                                                                                                                                                                                function updateStats() {
                                                                                                                                                                                                                                                                                                                                    const total = tasks.length;
                                                                                                                                                                                                                                                                                                                                        const completed = tasks.filter(t => t.completed).length;
                                                                                                                                                                                                                                                                                                                                            const pending = total - completed;

                                                                                                                                                                                                                                                                                                                                                if (statTotal) statTotal.textContent = total;
                                                                                                                                                                                                                                                                                                                                                    if (statPending) statPending.textContent = pending;
                                                                                                                                                                                                                                                                                                                                                        if (statCompleted) statCompleted.textContent = completed;
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        // Renderizar Tarefas na Tela
                                                                                                                                                                                                                                                                                                                                                        function renderTasks() {
                                                                                                                                                                                                                                                                                                                                                            updateStats();

                                                                                                                                                                                                                                                                                                                                                                // Filtrar tarefas
                                                                                                                                                                                                                                                                                                                                                                    let filteredTasks = tasks.filter(task => {
                                                                                                                                                                                                                                                                                                                                                                            const matchesSearch = task.title.toLowerCase().includes(currentSearchTerm);
                                                                                                                                                                                                                                                                                                                                                                                    if (!matchesSearch) return false;

                                                                                                                                                                                                                                                                                                                                                                                            if (currentFilter === 'pending') return !task.completed;
                                                                                                                                                                                                                                                                                                                                                                                                    if (currentFilter === 'completed') return task.completed;
                                                                                                                                                                                                                                                                                                                                                                                                            return true; // 'all'
                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                    if (filteredTasks.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                            if (tasksList) tasksList.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (emptyState) emptyState.classList.remove('hidden');
                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (emptyState) emptyState.classList.add('hidden');

                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (tasksList) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                tasksList.innerHTML = filteredTasks.map(task => `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="task-card ${task.completed ? 'completed' : ''}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="task-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="checkbox" class="task-checkbox" ${task.completed ? 'checked' : ''} onclick="toggleTask('${task.id}')">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="task-details">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span class="task-title">${escapeHTML(task.title)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="task-meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="badge-category"><i class="fa-solid fa-tag"></i> ${escapeHTML(task.category)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span class="badge-priority ${task.priority}">${task.priority.toUpperCase()}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${task.date !== 'Sem prazo' ? `<span class="task-date"><i class="fa-regular fa-calendar"></i> ${formatDate(task.date)}</span>` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button class="btn-delete" onclick="deleteTask('${task.id}')" title="Excluir Tarefa">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class="fa-solid fa-trash-can"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `).join('');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Funções Auxiliares de Formatação e Segurança
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function formatDate(dateStr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!dateStr) return '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const parts = dateStr.split('-');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (parts.length === 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return `${parts[2]}/${parts[1]}/${parts[0]}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return dateStr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function escapeHTML(str) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return str.replace(/[&<>'"]/g, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tag => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[tag] || tag)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Executar inicialização ao carregar o script
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            init();