// Elementos do DOM
const htmlEditor = document.getElementById('htmlEditor');
const cssEditor = document.getElementById('cssEditor');
const jsEditor = document.getElementById('jsEditor');
const preview = document.getElementById('preview');
const backBtn = document.querySelector('.back-btn');
const publishBtn = document.querySelector('.publish-btn');
const maximizeButtons = document.querySelectorAll('.maximize-btn');

// Função para atualizar a pré-visualização
function updatePreview() {
    const htmlCode = htmlEditor.value;
        const cssCode = cssEditor.value;
            const jsCode = jsEditor.value;
                
                    const completeCode = `
                            <!DOCTYPE html>
                                    <html lang="pt-BR">
                                            <head>
                                                        <meta charset="UTF-8">
                                                                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                <style>
                                                                                                ${cssCode}
                                                                                                            </style>
                                                                                                                    </head>
                                                                                                                            <body>
                                                                                                                                        ${htmlCode}
                                                                                                                                                    <script>
                                                                                                                                                                    ${jsCode}
                                                                                                                                                                                </script>
                                                                                                                                                                                        </body>
                                                                                                                                                                                                </html>
                                                                                                                                                                                                    `;
                                                                                                                                                                                                        
                                                                                                                                                                                                            preview.srcdoc = completeCode;
                                                                                                                                                                                                                saveToLocalStorage();
                                                                                                                                                                                                                }

                                                                                                                                                                                                                // Função para salvar no localStorage
                                                                                                                                                                                                                function saveToLocalStorage() {
                                                                                                                                                                                                                    localStorage.setItem('htmlCode', htmlEditor.value);
                                                                                                                                                                                                                        localStorage.setItem('cssCode', cssEditor.value);
                                                                                                                                                                                                                            localStorage.setItem('jsCode', jsEditor.value);
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                            // Função para carregar do localStorage
                                                                                                                                                                                                                            function loadFromLocalStorage() {
                                                                                                                                                                                                                                const htmlCode = localStorage.getItem('htmlCode') || '';
                                                                                                                                                                                                                                    const cssCode = localStorage.getItem('cssCode') || '';
                                                                                                                                                                                                                                        const jsCode = localStorage.getItem('jsCode') || '';
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                htmlEditor.value = htmlCode;
                                                                                                                                                                                                                                                    cssEditor.value = cssCode;
                                                                                                                                                                                                                                                        jsEditor.value = jsCode;
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                updatePreview();
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                // Função para maximizar editor
                                                                                                                                                                                                                                                                function setupMaximizeButtons() {
                                                                                                                                                                                                                                                                    maximizeButtons.forEach((btn, index) => {
                                                                                                                                                                                                                                                                            btn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                        const editorSection = btn.closest('.editor-section');
                                                                                                                                                                                                                                                                                                    editorSection.classList.toggle('maximized');
                                                                                                                                                                                                                                                                                                                btn.textContent = editorSection.classList.contains('maximized') ? 'Minimizar' : 'Maximizar';
                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                            // Event listeners para atualizar pré-visualização em tempo real
                                                                                                                                                                                                                                                                                                                            htmlEditor.addEventListener('input', updatePreview);
                                                                                                                                                                                                                                                                                                                            cssEditor.addEventListener('input', updatePreview);
                                                                                                                                                                                                                                                                                                                            jsEditor.addEventListener('input', updatePreview);

                                                                                                                                                                                                                                                                                                                            // Voltar para o início
                                                                                                                                                                                                                                                                                                                            backBtn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                if (confirm('Deseja voltar para o início? Suas alterações serão salvas.')) {
                                                                                                                                                                                                                                                                                                                                        window.location.href = '/';
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                            // Publicar no GitHub Pages
                                                                                                                                                                                                                                                                                                                                            publishBtn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                const htmlCode = htmlEditor.value;
                                                                                                                                                                                                                                                                                                                                                    const cssCode = cssEditor.value;
                                                                                                                                                                                                                                                                                                                                                        const jsCode = jsEditor.value;
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                if (!htmlCode.trim() || !cssCode.trim()) {
                                                                                                                                                                                                                                                                                                                                                                        alert('Por favor, preencha pelo menos o HTML e o CSS antes de publicar.');
                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                            const completeCode = `
                                                                                                                                                                                                                                                                                                                                                                                            <!DOCTYPE html>
                                                                                                                                                                                                                                                                                                                                                                                            <html lang="pt-BR">
                                                                                                                                                                                                                                                                                                                                                                                            <head>
                                                                                                                                                                                                                                                                                                                                                                                                <meta charset="UTF-8">
                                                                                                                                                                                                                                                                                                                                                                                                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                                                                                                                                                                                                                                                                                                        <style>
                                                                                                                                                                                                                                                                                                                                                                                                                ${cssCode}
                                                                                                                                                                                                                                                                                                                                                                                                                    </style>
                                                                                                                                                                                                                                                                                                                                                                                                                    </head>
                                                                                                                                                                                                                                                                                                                                                                                                                    <body>
                                                                                                                                                                                                                                                                                                                                                                                                                        ${htmlCode}
                                                                                                                                                                                                                                                                                                                                                                                                                            <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                    ${jsCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                        </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                            `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                    navigator.clipboard.writeText(completeCode).then(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert('Código copiado para a área de transferência! Cole em um arquivo index.html e publique no GitHub Pages.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }).catch(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('Erro ao copiar. Tente novamente.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Configurar botões de maximizar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setupMaximizeButtons();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Carregar dados salvos ao iniciar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            loadFromLocalStorage();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Adicionar estilos para modo maximizado
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const style = document.createElement('style');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style.textContent = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .editor-section.maximized {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        position: fixed;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                top: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        left: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: 100vw;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 100vh;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                z-index: 1000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border-radius: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .editor-section.maximized .editor {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border-radius: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.head.appendChild(style);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Fechar modo maximizado com ESC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener('keydown', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (e.key === 'Escape') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const maximizedSection = document.querySelector('.editor-section.maximized');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (maximizedSection) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                maximizedSection.classList.remove('maximized');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const btn = maximizedSection.querySelector('.maximize-btn');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        btn.textContent = 'Maximizar';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    