const cursor=document.querySelector(".cursor"),cursorOutline=document.querySelector(".cursor-outline");let mouseX=0,mouseY=0,outlineX=0,outlineY=0;
window.addEventListener("mousemove",e=>{mouseX=e.clientX;mouseY=e.clientY;cursor.style.left=`${mouseX}px`;cursor.style.top=`${mouseY}px`});
function animateCursor(){outlineX+=(mouseX-outlineX)*.15;outlineY+=(mouseY-outlineY)*.15;cursorOutline.style.left=`${outlineX}px`;cursorOutline.style.top=`${outlineY}px`;requestAnimationFrame(animateCursor)}animateCursor();
document.querySelectorAll("a,button,.tilt-card").forEach(el=>{el.addEventListener("mouseenter",()=>{cursorOutline.style.width="60px";cursorOutline.style.height="60px";cursorOutline.style.background="rgba(255,255,255,.05)"});el.addEventListener("mouseleave",()=>{cursorOutline.style.width="35px";cursorOutline.style.height="35px";cursorOutline.style.background="transparent"})});
const header=document.querySelector(".header");window.addEventListener("scroll",()=>header.classList.toggle("scrolled",window.scrollY>50));
const progressBar=document.querySelector(".scroll-progress");window.addEventListener("scroll",()=>{const h=document.documentElement.scrollHeight-document.documentElement.clientHeight;progressBar.style.width=`${(document.documentElement.scrollTop/h)*100}%`});
const phrases=["Desenvolvedor em formação.","Transformando ideias em código.","Criando experiências digitais.","Construindo o meu futuro.","O próximo projeto começa aqui."];const typingElement=document.getElementById("typing");let phraseIndex=0,characterIndex=0,deleting=false;
function typingEffect(){const phrase=phrases[phraseIndex];if(!deleting){typingElement.textContent=phrase.substring(0,characterIndex+1);characterIndex++;if(characterIndex===phrase.length){deleting=true;return setTimeout(typingEffect,1700)}}else{typingElement.textContent=phrase.substring(0,characterIndex-1);characterIndex--;if(characterIndex===0){deleting=false;phraseIndex=(phraseIndex+1)%phrases.length}}setTimeout(typingEffect,deleting?35:70)}typingEffect();
const revealElements=document.querySelectorAll(".reveal");const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")}),{threshold:.15});revealElements.forEach(el=>revealObserver.observe(el));
const stats=document.querySelectorAll(".stat-number");const statsObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,finalValue=Number(el.dataset.value);let value=0;const interval=setInterval(()=>{value+=Math.ceil(finalValue/40);if(value>=finalValue){value=finalValue;clearInterval(interval)}el.textContent=value},35);statsObserver.unobserve(el)}),{threshold:.5});stats.forEach(el=>statsObserver.observe(el));
const progressBars=document.querySelectorAll(".progress-bar");const progressObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.style.width=`${entry.target.dataset.progress}%`}),{threshold:.5});progressBars.forEach(el=>progressObserver.observe(el));
document.querySelectorAll(".tilt-card").forEach(card=>{card.addEventListener("mousemove",e=>{const r=card.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;card.style.transform=`perspective(1000px) rotateX(${(y-r.height/2)/20}deg) rotateY(${(r.width/2-x)/20}deg) translateY(-6px)`;card.style.setProperty("--mouse-x",`${x}px`);card.style.setProperty("--mouse-y",`${y}px`)});card.addEventListener("mouseleave",()=>card.style.transform="perspective(1000px) rotateX(0) rotateY(0) translateY(0)")});
function enablePhoto3D(selector){const card=document.querySelector(selector);if(!card)return;card.addEventListener("mousemove",e=>{const r=card.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;card.style.transform=`perspective(1200px) rotateX(${(r.height/2-y)/18}deg) rotateY(${(x-r.width/2)/18}deg) translateY(-4px)`});card.addEventListener("mouseleave",()=>card.style.transform="perspective(1200px) rotateX(0) rotateY(0) translateY(0)")};enablePhoto3D(".image-3d-card");enablePhoto3D(".childhood-card");
const scene=document.querySelector(".scene");window.addEventListener("mousemove",e=>{if(!scene)return;const x=(e.clientX/window.innerWidth-.5)*20,y=(e.clientY/window.innerHeight-.5)*20;scene.style.transform=`rotateX(${-y}deg) rotateY(${x}deg)`});
document.querySelectorAll(".magnetic-button").forEach(button=>{button.addEventListener("mousemove",e=>{const r=button.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;button.style.transform=`translate(${x*.22}px,${y*.22}px)`});button.addEventListener("mouseleave",()=>button.style.transform="translate(0,0)")});
const canvas=document.getElementById("particles"),ctx=canvas.getContext("2d");let particlesArray=[];function resizeCanvas(){canvas.width=innerWidth;canvas.height=innerHeight}resizeCanvas();addEventListener("resize",()=>{resizeCanvas();createParticles()});
class Particle{constructor(){this.x=Math.random()*canvas.width;this.y=Math.random()*canvas.height;this.size=Math.random()*1.5+.3;this.speedX=(Math.random()-.5)*.3;this.speedY=(Math.random()-.5)*.3;this.opacity=Math.random()*.4+.1}update(){this.x+=this.speedX;this.y+=this.speedY;if(this.x>canvas.width)this.x=0;if(this.x<0)this.x=canvas.width;if(this.y>canvas.height)this.y=0;if(this.y<0)this.y=canvas.height}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.size,0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${this.opacity})`;ctx.fill()}}
function createParticles(){particlesArray=[];const quantity=Math.min(100,Math.floor(innerWidth/12));for(let i=0;i<quantity;i++)particlesArray.push(new Particle())}createParticles();
function connectParticles(){for(let a=0;a<particlesArray.length;a++)for(let b=a;b<particlesArray.length;b++){const dx=particlesArray[a].x-particlesArray[b].x,dy=particlesArray[a].y-particlesArray[b].y,d=Math.sqrt(dx*dx+dy*dy);if(d<110){ctx.strokeStyle=`rgba(255,255,255,${(1-d/110)*.06})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(particlesArray[a].x,particlesArray[a].y);ctx.lineTo(particlesArray[b].x,particlesArray[b].y);ctx.stroke()}}}
function animateParticles(){ctx.clearRect(0,0,canvas.width,canvas.height);particlesArray.forEach(p=>{p.update();p.draw()});connectParticles();requestAnimationFrame(animateParticles)}animateParticles();
const menuButton=document.getElementById("menuButton"),navLinks=document.querySelector(".nav-links");menuButton.addEventListener("click",()=>navLinks.classList.toggle("active"));document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>navLinks.classList.remove("active")));
window.addEventListener("scroll",()=>{const y=scrollY,g1=document.querySelector(".glow-one"),g2=document.querySelector(".glow-two");if(g1)g1.style.transform=`translateY(${y*.08}px)`;if(g2)g2.style.transform=`translateY(${-y*.05}px)`});
const sections=document.querySelectorAll("section[id]"),navItems=document.querySelectorAll(".nav-links a");window.addEventListener("scroll",()=>{let current="";sections.forEach(s=>{if(scrollY>=s.offsetTop-300)current=s.id});navItems.forEach(a=>{a.style.color=a.getAttribute("href")===`#${current}`?"#fff":"#aaa"})});
document.getElementById("year").textContent=new Date().getFullYear();
console.log("%c NICHOLAS NAMURA","font-size:30px;font-weight:bold;color:white;background:black;padding:10px;");
