// ESTADO DA APLICAÇÃO (Com LocalStorage)
let tarefas = JSON.parse(localStorage.getItem('taskmaster_tarefas')) || [
  { codigo: 101, titulo: "Configurar ambiente de desenvolvimento Node.js", prioridade: 1, concluida: false },
    { codigo: 102, titulo: "Desenvolver protótipo da interface no Figma", prioridade: 2, concluida: true },
      { codigo: 103, titulo: "Revisão de código e testes unitários", prioridade: 3, concluida: false }
      ];

      let filtroAtual = 'todas';
      let buscaTermo = '';

      const prioridadeMap = {
        1: { texto: "Alta", classe: "prio-alta", icon: "fa-fire" },
          2: { texto: "Média", classe: "prio-media", icon: "fa-triangle-exclamation" },
            3: { texto: "Baixa", classe: "prio-baixa", icon: "fa-leaf" }
            };

            // ELEMENTOS
            const formTarefa = document.getElementById('form-tarefa');
            const tabelaTarefas = document.getElementById('tabela-tarefas');
            const searchInput = document.getElementById('search-input');
            const modalPrio = document.getElementById('modal-prio');
            const formAlterarPrio = document.getElementById('form-alterar-prio');

            // TOAST NOTIFICAÇÕES
            function showToast(message, icon = 'fa-info-circle') {
              const container = document.getElementById('toast-container');
                const toast = document.createElement('div');
                  toast.className = 'toast';
                    toast.innerHTML = `<i class="fa-solid ${icon}" style="color: var(--primary);"></i> <span>${message}</span>`;
                      container.appendChild(toast);

                        setTimeout(() => {
                            toast.style.opacity = '0';
                                toast.style.transform = 'translateX(100%)';
                                    setTimeout(() => toast.remove(), 300);
                                      }, 3000);
                                      }

                                      // SALVAR NO LOCALSTORAGE
                                      function salvarDados() {
                                        localStorage.setItem('taskmaster_tarefas', JSON.stringify(tarefas));
                                          atualizarMetricas();
                                          }

                                          // ATUALIZAR DASHBOARD DE MÉTRICAS
                                          function atualizarMetricas() {
                                            document.getElementById('stat-total').textContent = tarefas.length;
                                              document.getElementById('stat-concluidas').textContent = tarefas.filter(t => t.concluida).length;
                                                document.getElementById('stat-pendentes').textContent = tarefas.filter(t => !t.concluida).length;
                                                  document.getElementById('stat-alta-prio').textContent = tarefas.filter(t => Number(t.prioridade) === 1).length;
                                                  }

                                                  // RENDERIZAR TABELA
                                                  function renderizarTarefas() {
                                                    tabelaTarefas.innerHTML = '';

                                                      let tarefasFiltradas = tarefas.filter(t => {
                                                          const atendeFiltro = 
                                                                filtroAtual === 'todas' || 
                                                                      (filtroAtual === 'concluidas' && t.concluida) || 
                                                                            (filtroAtual === 'pendentes' && !t.concluida);
                                                                                
                                                                                    const atendeBusca = 
                                                                                          t.titulo.toLowerCase().includes(buscaTermo.toLowerCase()) || 
                                                                                                t.codigo.toString().includes(buscaTermo);

                                                                                                    return atendeFiltro && atendeBusca;
                                                                                                      });

                                                                                                        if (tarefasFiltradas.length === 0) {
                                                                                                            tabelaTarefas.innerHTML = `
                                                                                                                  <tr>
                                                                                                                          <td colspan="5">
                                                                                                                                    <div class="empty-state">
                                                                                                                                                <i class="fa-solid fa-inbox"></i>
                                                                                                                                                            <p>Nenhuma tarefa encontrada.</p>
                                                                                                                                                                      </div>
                                                                                                                                                                              </td>
                                                                                                                                                                                    </tr>
                                                                                                                                                                                        `;
                                                                                                                                                                                            return;
                                                                                                                                                                                              }

                                                                                                                                                                                                tarefasFiltradas.forEach(t => {
                                                                                                                                                                                                    const prio = prioridadeMap[t.prioridade];
                                                                                                                                                                                                        const tr = document.createElement('tr');
                                                                                                                                                                                                            
                                                                                                                                                                                                                tr.innerHTML = `
                                                                                                                                                                                                                      <td><span class="code-badge">#${t.codigo}</span></td>
                                                                                                                                                                                                                            <td><span class="task-title ${t.concluida ? 'completed' : ''}">${t.titulo}</span></td>
                                                                                                                                                                                                                                  <td>
                                                                                                                                                                                                                                          <span class="prio-tag ${prio.classe}">
                                                                                                                                                                                                                                                    <i class="fa-solid ${prio.icon}"></i> ${prio.texto}
                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                <span class="status-pill ${t.concluida ? 'concluida' : 'pendente'}">
                                                                                                                                                                                                                                                                                          <i class="fa-solid ${t.concluida ? 'fa-circle-check' : 'fa-clock'}"></i>
                                                                                                                                                                                                                                                                                                    ${t.concluida ? 'Concluída' : 'Pendente'}
                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                                                                <div class="action-btns" style="justify-content: flex-end;">
                                                                                                                                                                                                                                                                                                                                          <button class="action-btn" title="Alternar Status" onclick="toggleConcluida(${t.codigo})">
                                                                                                                                                                                                                                                                                                                                                      <i class="fa-solid ${t.concluida ? 'fa-rotate-left' : 'fa-check'}"></i>
                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                          <button class="action-btn" title="Alterar Prioridade" onclick="abrirModal(${t.codigo})">
                                                                                                                                                                                                                                                                                                                                                                                      <i class="fa-solid fa-pen-to-square"></i>
                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                          <button class="action-btn delete" title="Excluir" onclick="deletarTarefa(${t.codigo})">
                                                                                                                                                                                                                                                                                                                                                                                                                      <i class="fa-solid fa-trash"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                          tabelaTarefas.appendChild(tr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            // EVENTO: ADICIONAR TAREFA
                                                                                                                                                                                                                                                                                                                                                                                                                                                            formTarefa.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const codigo = Number(document.getElementById('codigo').value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const titulo = document.getElementById('titulo').value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const prioridade = Number(document.getElementById('prioridade').value);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (tarefas.some(t => t.codigo === codigo)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showToast('Já existe uma tarefa com esse Código/ID!', 'fa-triangle-exclamation');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tarefas.push({ codigo, titulo, prioridade, concluida: false });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      salvarDados();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          formTarefa.reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showToast('Tarefa cadastrada com sucesso!', 'fa-circle-check');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // EVENTOS: STATUS E EXCLUSÃO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function toggleConcluida(codigo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              tarefas = tarefas.map(t => t.codigo === codigo ? { ...t, concluida: !t.concluida } : t);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                salvarDados();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    showToast('Status da tarefa atualizado!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function deletarTarefa(codigo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tarefas = tarefas.filter(t => t.codigo !== codigo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        salvarDados();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showToast('Tarefa removida com sucesso.', 'fa-trash');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // EVENTOS: MODAL DE PRIORIDADE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function abrirModal(codigo) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const tarefa = tarefas.find(t => t.codigo === codigo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!tarefa) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('modal-codigo').value = tarefa.codigo;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('modal-task-title').textContent = `Tarefa: #${tarefa.codigo} - ${tarefa.titulo}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById('modal-prioridade').value = tarefa.prioridade;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        modalPrio.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function fecharModal() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          modalPrio.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          formAlterarPrio.addEventListener('submit', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const codigo = Number(document.getElementById('modal-codigo').value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const novaPrio = Number(document.getElementById('modal-prioridade').value);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tarefas = tarefas.map(t => t.codigo === codigo ? { ...t, prioridade: novaPrio } : t);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    salvarDados();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fecharModal();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          showToast('Prioridade alterada com sucesso!', 'fa-sliders');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // BUSCA E FILTROS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          searchInput.addEventListener('input', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            buscaTermo = e.target.value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.querySelectorAll('.pill-btn').forEach(btn => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                btn.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.querySelectorAll('.pill-btn').forEach(b => b.classList.remove('active'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        btn.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filtroAtual = btn.getAttribute('data-filter');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // INICIALIZAÇÃO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderizarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  atualizarMetricas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  