document.addEventListener("DOMContentLoaded", function () {

      // CURTIR
        const botoesCurtir = document.querySelectorAll(".btn-curtir");

          botoesCurtir.forEach(function (botao) {

              botao.addEventListener("click", function () {

                    let contador = botao.querySelector("span");
                          let quantidade = Number(contador.textContent);

                                if (botao.classList.contains("curtido")) {
                                        quantidade--;
                                                botao.classList.remove("curtido");
                                                        botao.innerHTML = "♡ Curtir <span>" + quantidade + "</span>";
                                                              } else {
                                                                      quantidade++;
                                                                              botao.classList.add("curtido");
                                                                                      botao.innerHTML = "♥ Curtido <span>" + quantidade + "</span>";
                                                                                            }

                                                                                                });

                                                                                                  });


                                                                                                    // COMENTAR
                                                                                                      function ativarComentarios() {

                                                                                                          const botoesComentar =
                                                                                                                document.querySelectorAll(".btn-comentar");

                                                                                                                    botoesComentar.forEach(function (botao) {

                                                                                                                          if (botao.dataset.ativo === "true") {
                                                                                                                                  return;
                                                                                                                                        }

                                                                                                                                              botao.dataset.ativo = "true";

                                                                                                                                                    botao.addEventListener("click", function () {

                                                                                                                                                            const postagem = botao.closest(".postagem");
                                                                                                                                                                    const area = postagem.querySelector(".area-comentario");

                                                                                                                                                                            if (area.querySelector(".comentario-box")) {
                                                                                                                                                                                      return;
                                                                                                                                                                                              }

                                                                                                                                                                                                      const caixa = document.createElement("div");
                                                                                                                                                                                                              caixa.className = "comentario-box";

                                                                                                                                                                                                                      caixa.innerHTML = `
                                                                                                                                                                                                                                <input type="text" placeholder="Escreva um comentário...">
                                                                                                                                                                                                                                          <button>Enviar</button>
                                                                                                                                                                                                                                                  `;

                                                                                                                                                                                                                                                          area.appendChild(caixa);

                                                                                                                                                                                                                                                                  const input = caixa.querySelector("input");
                                                                                                                                                                                                                                                                          const enviar = caixa.querySelector("button");

                                                                                                                                                                                                                                                                                  input.focus();

                                                                                                                                                                                                                                                                                          enviar.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                                    const texto = input.value.trim();

                                                                                                                                                                                                                                                                                                              if (texto === "") {
                                                                                                                                                                                                                                                                                                                          alert("Digite um comentário.");
                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                          const comentario = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                    comentario.className = "comentario";

                                                                                                                                                                                                                                                                                                                                                                              comentario.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                          "<strong>Nara:</strong> " + texto;

                                                                                                                                                                                                                                                                                                                                                                                                    area.appendChild(comentario);

                                                                                                                                                                                                                                                                                                                                                                                                              caixa.remove();

                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                    ativarComentarios();


                                                                                                                                                                                                                                                                                                                                                                                                                                      // PUBLICAR
                                                                                                                                                                                                                                                                                                                                                                                                                                        const btnPublicar =
                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("btnPublicar");

                                                                                                                                                                                                                                                                                                                                                                                                                                              btnPublicar.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                  const texto =
                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("textoPublicacao").value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const imagem =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById("imagemPublicacao").value.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (texto === "") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("Escreva alguma coisa antes de publicar. 💕");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const feed =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById("feedPostagens");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const novaPostagem =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.createElement("article");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              novaPostagem.className = "postagem";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let imagemHTML = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (imagem !== "") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            imagemHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              class="imagem-post"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src="${imagem}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alt="Imagem da publicação"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        novaPostagem.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div class="post-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div class="avatar rosa">N</div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Nara</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>Agora</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p class="texto-post">${texto}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${imagemHTML}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="acoes">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button class="btn-curtir">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ♡ Curtir <span>0</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button class="btn-comentar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              💬 Comentar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="area-comentario"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          feed.insertBefore(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                novaPostagem,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      feed.firstElementChild
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Limpa os campos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById("textoPublicacao").value = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById("imagemPublicacao").value = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Ativa Curtir da nova postagem
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const novoCurtir =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    novaPostagem.querySelector(".btn-curtir");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        novoCurtir.addEventListener("click", function () {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let contador =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      novoCurtir.querySelector("span");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let quantidade =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Number(contador.textContent);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (novoCurtir.classList.contains("curtido")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  quantidade--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          novoCurtir.classList.remove("curtido");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  novoCurtir.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "♡ Curtir <span>" + quantidade + "</span>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          quantidade++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  novoCurtir.classList.add("curtido");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          novoCurtir.innerHTML =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "♥ Curtido <span>" + quantidade + "</span>";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Ativa comentar da nova postagem
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ativarComentarios();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Volta para o começo do feed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              novaPostagem.scrollIntoView({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    behavior: "smooth",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          block: "center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
})