// Banco de dados contendo as informações, links e caminhos das imagens
const museumData = [
    {
            title: "O Início: Sporting CP",
                    period: "2002 - 2003",
                            image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800", // Substitua pela foto do Sporting se quiser
                                    description: "Onde tudo começou. Um jovem magro com velocidade espantosa impressiona os olheiros em Lisboa. Sua atuação lendária contra o Manchester United em um amistoso de inauguração de estádio mudou o rumo da história do futebol mundial.",
                                            url: "https://www.sporting.pt/",
                                                    stats: [
                                                                { value: "31", label: "Jogos" },
                                                                            { value: "5", label: "Gols" },
                                                                                        { value: "3", label: "Assistências" },
                                                                                                    { value: "0", label: "Ballon d'Or" }
                                                                                                            ]
                                                                                                                },
                                                                                                                    {
                                                                                                                            title: "A Lapidação: Manchester United",
                                                                                                                                    period: "2003 - 2009",
                                                                                                                                            image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800", // Substitua pela foto do United
                                                                                                                                                    description: "Sob a batuta de Sir Alex Ferguson, Ronaldo herda a mítica camisa 7. Ele se transforma de um ponta habilidoso em uma máquina de gols imparável, conquistando sua primeira Champions League e sua primeira Bola de Ouro em 2008.",
                                                                                                                                                            url: "https://www.manutd.com/",
                                                                                                                                                                    stats: [
                                                                                                                                                                                { value: "292", label: "Jogos" },
                                                                                                                                                                                            { value: "118", label: "Gols" },
                                                                                                                                                                                                        { value: "1", label: "Ballon d'Or" },
                                                                                                                                                                                                                    { value: "1x", label: "Champions League" }
                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                            title: "O Ápice: Real Madrid",
                                                                                                                                                                                                                                                    period: "2009 - 2018",
                                                                                                                                                                                                                                                            image: "https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=800", // Substitua pela foto do Real Madrid
                                                                                                                                                                                                                                                                    description: "A era dos recordes impossíveis. Tornou-se o maior artilheiro da história dos Merengues com uma média absurda de mais de um gol por partida. Faturou 4 títulos de Champions League e consolidou sua rivalidade histórica no topo do mundo.",
                                                                                                                                                                                                                                                                            url: "https://www.realmadrid.com/",
                                                                                                                                                                                                                                                                                    stats: [
                                                                                                                                                                                                                                                                                                { value: "438", label: "Jogos" },
                                                                                                                                                                                                                                                                                                            { value: "450", label: "Gols" },
                                                                                                                                                                                                                                                                                                                        { value: "4", label: "Ballon d'Or" },
                                                                                                                                                                                                                                                                                                                                    { value: "4x", label: "Champions League" }
                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                            title: "O Desafio: Juventus",
                                                                                                                                                                                                                                                                                                                                                                    period: "2018 - 2021",
                                                                                                                                                                                                                                                                                                                                                                            image: "https://images.unsplash.com/photo-1540747737956-37872404a8c1?w=800", // Substitua pela foto da Juventus
                                                                                                                                                                                                                                                                                                                                                                                    description: "Buscando novos desafios, desembarca na Itália. Ele dominou o futebol italiano, quebrando recordes de velocidade para alcançar 100 gols por um clube e faturando duas vezes a Serie A, provando sua capacidade de vencer em qualquer lugar.",
                                                                                                                                                                                                                                                                                                                                                                                            url: "https://www.juventus.com/",
                                                                                                                                                                                                                                                                                                                                                                                                    stats: [
                                                                                                                                                                                                                                                                                                                                                                                                                { value: "134", label: "Jogos" },
                                                                                                                                                                                                                                                                                                                                                                                                                            { value: "101", label: "Gols" },
                                                                                                                                                                                                                                                                                                                                                                                                                                        { value: "2x", label: "Campeão Italiano" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    { value: "1x", label: "Artilheiro da Liga" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: "A Conquista da Ásia: Al-Nassr",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    period: "2023 - Presente",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800", // Substitua pela foto do Al-Nassr
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description: "Cristiano choca o mundo novamente ao migrar para o futebol saudita, abrindo as portas para uma nova era de estrelas globais na Ásia. Mesmo veterano, continuou empilhando gols e terminando anos civis como o maior artilheiro do planeta.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url: "https://alnassr.sa/",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stats: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { value: "85+", label: "Jogos" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { value: "75+", label: "Gols" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { value: "1x", label: "Copa dos Campeões" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { value: "38+", label: "Anos de Idade" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: "Orgulho Nacional: Seleção de Portugal",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    period: "2003 - Presente",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            image: "https://images.unsplash.com/photo-1551958219-acbc608c6d77?w=800", // Substitua pela foto de Portugal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description: "O maior herói da história do futebol português. Líder incontestável, tornou-se o maior artilheiro de seleções de todos os tempos. Carregou o país rumo às maiores conquistas de sua história: a Eurocopa de 2016 e a Nations League de 2019.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url: "https://www.fpf.pt/",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stats: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { value: "210+", label: "Jogos" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { value: "130+", label: "Gols" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { value: "1x", label: "Eurocopa" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { value: "1x", label: "Nations League" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let currentHall = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const museumHall = document.getElementById("museumHall");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const eraLink = document.getElementById("eraLink");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const prevBtn = document.getElementById("prevBtn");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const nextBtn = document.getElementById("nextBtn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function renderHall(index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const data = museumData[index];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let statsHTML = `<div class="stats-grid">`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data.stats.forEach(stat => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        statsHTML += `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="stat-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="stat-value">${stat.value}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="stat-label">${stat.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                statsHTML += `</div>`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    museumHall.classList.remove("fade-in");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        void museumHall.offsetWidth; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            museumHall.classList.add("fade-in");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Injetando o conteúdo incluindo a nova tag img configurada dinamicamente
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    museumHall.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 class="era-title">${data.title}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="era-period">${data.period}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img src="${data.image}" alt="${data.title}" class="era-image">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="era-description">${data.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${statsHTML}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    eraLink.href = data.url;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prevBtn.disabled = index === 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nextBtn.disabled = index === museumData.length - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function navigateHall(direction) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currentHall += direction;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderHall(currentHall);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    window.onload = function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderHall(currentHall);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        