// Smooth scroll e navegação ativa
document.addEventListener('DOMContentLoaded', () => {
    const navLinks = document.querySelectorAll('.nav-link');
        const sections = document.querySelectorAll('section, header');

            // Smooth scroll ao clicar nos links
                navLinks.forEach(link => {
                        link.addEventListener('click', (e) => {
                                    e.preventDefault();
                                                const targetId = link.getAttribute('href');
                                                            const target = document.querySelector(targetId);
                                                                        
                                                                                    if (target) {
                                                                                                    const offset = 70; // altura da navbar
                                                                                                                    const top = target.getBoundingClientRect().top + window.pageYOffset - offset;
                                                                                                                                    
                                                                                                                                                    window.scrollTo({
                                                                                                                                                                        top: top,
                                                                                                                                                                                            behavior: 'smooth'
                                                                                                                                                                                                            });
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                        // Atualiza link ativo conforme scroll
                                                                                                                                                                                                                                            function updateActiveLink() {
                                                                                                                                                                                                                                                    let current = '';
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    sections.forEach(section => {
                                                                                                                                                                                                                                                                                const sectionTop = section.offsetTop - 100;
                                                                                                                                                                                                                                                                                            const sectionHeight = section.offsetHeight;
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                    if (window.pageYOffset >= sectionTop && window.pageYOffset < sectionTop + sectionHeight) {
                                                                                                                                                                                                                                                                                                                                    current = section.getAttribute('id') || 'inicio';
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                // Fallback para o topo
                                                                                                                                                                                                                                                                                                                                                                        if (window.pageYOffset < 150) {
                                                                                                                                                                                                                                                                                                                                                                                    current = 'inicio';
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    navLinks.forEach(link => {
                                                                                                                                                                                                                                                                                                                                                                                                                link.classList.remove('active');
                                                                                                                                                                                                                                                                                                                                                                                                                            const href = link.getAttribute('href').replace('#', '');
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (href === current || (current === 'sobre' && href === 'inicio')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    link.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Mapear seções
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (current === 'galeria' && href === 'galeria') link.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (current === 'colunas' && href === 'colunas') link.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (current === 'contatos' && href === 'contatos') link.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ((current === 'inicio' || current === 'sobre') && href === 'inicio') link.classList.add('active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.addEventListener('scroll', updateActiveLink);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updateActiveLink();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Efeito de hover suave nos placeholders da galeria
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const galleryItems = document.querySelectorAll('.placeholder-img');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        galleryItems.forEach(item => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            item.style.transform = 'scale(0.97)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        item.style.transform = '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 150);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('%c🎮 Meu Blog de Games — Gabriel The Gamer', 'color: #60a5fa; font-size: 14px; font-weight: bold;');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log('%cTerraria 1.4.5.7 — Atualização carregada!', 'color: #86efac; font-size: 12px;');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        