const questions = [

        {
                question: "🔐 Qual é uma boa prática para criar uma senha?",
                        answers: [
                                    "Usar 123456",
                                                "Usar informações pessoais",
                                                            "Usar uma senha forte e difícil de adivinhar",
                                                                        "Usar a mesma senha em todos os sites"
                                                                                ],
                                                                                        correct: 2
                                                                                            },

                                                                                                {
                                                                                                        question: "📱 O que devemos fazer ao receber um link suspeito?",
                                                                                                                answers: [
                                                                                                                            "Clicar imediatamente",
                                                                                                                                        "Enviar para todos os amigos",
                                                                                                                                                    "Verificar antes de clicar",
                                                                                                                                                                "Colocar nossa senha"
                                                                                                                                                                        ],
                                                                                                                                                                                correct: 2
                                                                                                                                                                                    },

                                                                                                                                                                                        {
                                                                                                                                                                                                question: "🌐 O que é a internet?",
                                                                                                                                                                                                        answers: [
                                                                                                                                                                                                                    "Uma rede que conecta computadores e dispositivos",
                                                                                                                                                                                                                                "Um aplicativo de mensagens",
                                                                                                                                                                                                                                            "Um jogo",
                                                                                                                                                                                                                                                        "Um tipo de computador"
                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                        correct: 0
                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                        question: "🛡️ Para que serve um antivírus?",
                                                                                                                                                                                                                                                                                                answers: [
                                                                                                                                                                                                                                                                                                            "Para deixar a internet mais rápida",
                                                                                                                                                                                                                                                                                                                        "Para ajudar a detectar ameaças digitais",
                                                                                                                                                                                                                                                                                                                                    "Para criar senhas",
                                                                                                                                                                                                                                                                                                                                                "Para fazer chamadas"
                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                correct: 1
                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                question: "🚨 O que é phishing?",
                                                                                                                                                                                                                                                                                                                                                                                        answers: [
                                                                                                                                                                                                                                                                                                                                                                                                    "Um jogo online",
                                                                                                                                                                                                                                                                                                                                                                                                                "Uma tentativa de enganar alguém para obter informações",
                                                                                                                                                                                                                                                                                                                                                                                                                            "Um navegador",
                                                                                                                                                                                                                                                                                                                                                                                                                                        "Uma rede social"
                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                        correct: 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        question: "🔒 Devemos compartilhar nossa senha com qualquer pessoa?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                answers: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Sim",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Somente com desconhecidos",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Não",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Sempre nas redes sociais"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                correct: 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let currentQuestion = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let score = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const question = document.getElementById("question");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const answers = document.getElementById("answers");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const scoreText = document.getElementById("score");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const message = document.getElementById("message");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const startButton = document.getElementById("startButton");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function startGame() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currentQuestion = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            score = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scoreText.textContent = score;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message.textContent = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startButton.style.display = "none";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            showQuestion();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function showQuestion() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (currentQuestion >= questions.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        finishGame();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const current = questions[currentQuestion];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            question.textContent = current.question;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                answers.innerHTML = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    current.answers.forEach((answer, index) => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const button = document.createElement("button");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    button.classList.add("answer");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            button.textContent = answer;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    button.onclick = () => checkAnswer(index, button);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            answers.appendChild(button);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function checkAnswer(index, button) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const current = questions[currentQuestion];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const allButtons =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.querySelectorAll(".answer");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    allButtons.forEach(btn => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            btn.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (index === current.correct) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            score++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scoreText.textContent = score;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            button.classList.add("correct");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message.textContent = "✅ Resposta correta!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                button.classList.add("wrong");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        allButtons[current.correct].classList.add("correct");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message.textContent = "❌ Resposta incorreta!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(() => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                currentQuestion++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message.textContent = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                showQuestion();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 1200);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function finishGame() {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        question.textContent = "🎉 Jogo terminado!";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            answers.innerHTML = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message.textContent =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `Você acertou ${score} de ${questions.length} perguntas!`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            startButton.textContent = "Jogar Novamente";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                startButton.style.display = "inline-block";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
]