const perguntas = [
        {
                pergunta: "O que significa a sigla HTML?",
                        opcoes: [
                                    "Hyper Text Markup Language",
                                                "High Tech Modern Language",
                                                            "Home Tool Markup Language",
                                                                        "Hyperlinks and Text Mark Language"
                                                                                ],
                                                                                        correta: 0
                                                                                            },
                                                                                                {
                                                                                                        pergunta: "Qual é a função principal do CSS?",
                                                                                                                opcoes: [
                                                                                                                            "Criar interatividade nos sites",
                                                                                                                                        "Definir o estilo e a aparência visual dos sites",
                                                                                                                                                    "Gerenciar bancos de dados",
                                                                                                                                                                "Navegar na internet"
                                                                                                                                                                        ],
                                                                                                                                                                                correta: 1
                                                                                                                                                                                    },
                                                                                                                                                                                        {
                                                                                                                                                                                                pergunta: "O que é a Internet?",
                                                                                                                                                                                                        opcoes: [
                                                                                                                                                                                                                    "Um único site muito grande",
                                                                                                                                                                                                                                "Um programa de computador",
                                                                                                                                                                                                                                            "Uma rede mundial de computadores conectados",
                                                                                                                                                                                                                                                        "Um tipo de cabo elétrico"
                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                        correta: 2
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            ];

                                                                                                                                                                                                                                                                            let indiceAtual = 0;
                                                                                                                                                                                                                                                                            let pontuacao = 0;

                                                                                                                                                                                                                                                                            const btnInicio = document.getElementById('btnInicio');
                                                                                                                                                                                                                                                                            const divInicio = document.querySelector('.caixa-jogo');
                                                                                                                                                                                                                                                                            const divPerguntas = document.getElementById('perguntas');
                                                                                                                                                                                                                                                                            const divResultado = document.getElementById('resultado');
                                                                                                                                                                                                                                                                            const numeroPergunta = document.getElementById('numero-pergunta');
                                                                                                                                                                                                                                                                            const textoPergunta = document.getElementById('texto-pergunta');
                                                                                                                                                                                                                                                                            const divRespostas = document.getElementById('respostas');
                                                                                                                                                                                                                                                                            const feedback = document.getElementById('feedback');
                                                                                                                                                                                                                                                                            const btnProximo = document.getElementById('btnProximo');
                                                                                                                                                                                                                                                                            const textoPontuacao = document.getElementById('pontuacao');
                                                                                                                                                                                                                                                                            const btnReiniciar = document.getElementById('btnReiniciar');

                                                                                                                                                                                                                                                                            btnInicio.addEventListener('click', iniciarJogo);
                                                                                                                                                                                                                                                                            btnProximo.addEventListener('click', proximaPergunta);
                                                                                                                                                                                                                                                                            btnReiniciar.addEventListener('click', reiniciarJogo);

                                                                                                                                                                                                                                                                            function iniciarJogo() {
                                                                                                                                                                                                                                                                                divInicio.classList.add('escondido');
                                                                                                                                                                                                                                                                                    divPerguntas.classList.remove('escondido');
                                                                                                                                                                                                                                                                                        indiceAtual = 0;
                                                                                                                                                                                                                                                                                            pontuacao = 0;
                                                                                                                                                                                                                                                                                                mostrarPergunta();
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                function mostrarPergunta() {
                                                                                                                                                                                                                                                                                                    feedback.textContent = '';
                                                                                                                                                                                                                                                                                                        feedback.className = 'feedback';
                                                                                                                                                                                                                                                                                                            btnProximo.classList.add('escondido');
                                                                                                                                                                                                                                                                                                                divRespostas.innerHTML = '';
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                        const perguntaAtual = perguntas[indiceAtual];
                                                                                                                                                                                                                                                                                                                            numeroPergunta.textContent = `Pergunta ${indiceAtual + 1}`;
                                                                                                                                                                                                                                                                                                                                textoPergunta.textContent = perguntaAtual.pergunta;
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        perguntaAtual.opcoes.forEach((opcao, indice) => {
                                                                                                                                                                                                                                                                                                                                                const botao = document.createElement('button');
                                                                                                                                                                                                                                                                                                                                                        botao.textContent = opcao;
                                                                                                                                                                                                                                                                                                                                                                botao.classList.add('btn', 'opcao');
                                                                                                                                                                                                                                                                                                                                                                        botao.addEventListener('click', () => verificarResposta(indice));
                                                                                                                                                                                                                                                                                                                                                                                divRespostas.appendChild(botao);
                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                    function verificarResposta(indiceEscolhido) {
                                                                                                                                                                                                                                                                                                                                                                                        const correta = perguntas[indiceAtual].correta;
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                if (indiceEscolhido === correta) {
                                                                                                                                                                                                                                                                                                                                                                                                        feedback.textContent = '✅ Correto! Parabéns!';
                                                                                                                                                                                                                                                                                                                                                                                                                feedback.classList.add('correto');
                                                                                                                                                                                                                                                                                                                                                                                                                        pontuacao++;
                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                    feedback.textContent = '❌ Ops! Resposta errada.';
                                                                                                                                                                                                                                                                                                                                                                                                                                            feedback.classList.add('errado');
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        btnProximo.classList.remove('escondido');
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        function proximaPergunta() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            indiceAtual++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (indiceAtual < perguntas.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mostrarPergunta();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mostrarResultado();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function mostrarResultado() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                divPerguntas.classList.add('escondido');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    divResultado.classList.remove('escondido');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textoPontuacao.textContent = pontuacao;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function reiniciarJogo() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            divResultado.classList.add('escondido');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                divInicio.classList.remove('escondido');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
]