let tarefas = [];


// CADASTRAR UMA NOVA TAREFA
function cadastrarTarefa() {

    let codigo = document.getElementById("codigo").value;
        let titulo = document.getElementById("titulo").value;
            let prioridade = Number(document.getElementById("prioridade").value);

                // Verificar se o título possui pelo menos 5 caracteres
                    if (titulo.length < 5) {
                            alert("O título deve ter no mínimo 5 caracteres.");
                                    return;
                                        }

                                            // Verificar a prioridade
                                                if (prioridade < 1 || prioridade > 3) {
                                                        alert("A prioridade deve estar entre 1 e 3.");
                                                                return;
                                                                    }

                                                                        let tarefa = {
                                                                                codigo: codigo,
                                                                                        titulo: titulo,
                                                                                                prioridade: prioridade,
                                                                                                        concluida: false
                                                                                                            };

                                                                                                                tarefas.push(tarefa);

                                                                                                                    alert("Tarefa cadastrada com sucesso!");

                                                                                                                        document.getElementById("codigo").value = "";
                                                                                                                            document.getElementById("titulo").value = "";

                                                                                                                                listarTarefas();
                                                                                                                                }


                                                                                                                                // LISTAR AS TAREFAS
                                                                                                                                function listarTarefas() {

                                                                                                                                    let lista = document.getElementById("listaTarefas");

                                                                                                                                        lista.innerHTML = "";

                                                                                                                                            if (tarefas.length === 0) {
                                                                                                                                                    lista.innerHTML = "<p>Nenhuma tarefa cadastrada.</p>";
                                                                                                                                                            return;
                                                                                                                                                                }

                                                                                                                                                                    for (let i = 0; i < tarefas.length; i++) {

                                                                                                                                                                            let tarefa = tarefas[i];

                                                                                                                                                                                    let status = tarefa.concluida
                                                                                                                                                                                                ? "Concluída"
                                                                                                                                                                                                            : "Pendente";

                                                                                                                                                                                                                    let classe = tarefa.concluida
                                                                                                                                                                                                                                ? "tarefa concluida"
                                                                                                                                                                                                                                            : "tarefa";

                                                                                                                                                                                                                                                    lista.innerHTML += `
                                                                                                                                                                                                                                                                <div class="${classe}">

                                                                                                                                                                                                                                                                                <h3>${tarefa.titulo}</h3>

                                                                                                                                                                                                                                                                                                <p><strong>Código:</strong> ${tarefa.codigo}</p>

                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                    <strong>Prioridade:</strong>
                                                                                                                                                                                                                                                                                                                                                        ${tarefa.prioridade}
                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                            <strong>Status:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                ${status}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="botoes">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class="btn-concluir"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onclick="concluirTarefa(${i})">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Marcar como concluída
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            class="btn-prioridade"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onclick="alterarPrioridade(${i})">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Alterar prioridade
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // MARCAR TAREFA COMO CONCLUÍDA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function concluirTarefa(indice) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tarefas[indice].concluida = true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ALTERAR PRIORIDADE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function alterarPrioridade(indice) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let novaPrioridade = Number(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            prompt("Digite a nova prioridade (1, 2 ou 3):")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (novaPrioridade < 1 || novaPrioridade > 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert("A prioridade deve ser um valor entre 1 e 3.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tarefas[indice].prioridade = novaPrioridade;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Mostrar a lista quando a página abrir
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                listarTarefas();