// Lista de produtos
let produtos = [
    {
            codigo: 1,
                    descricao: "Cadeira Gamer",
                            quantidade: 12,
                                    valor: 699.00
                                        },
                                            {
                                                    codigo: 2,
                                                            descricao: "Mouse Logitech",
                                                                    quantidade: 38,
                                                                            valor: 97.00
                                                                                },
                                                                                    {
                                                                                            codigo: 3,
                                                                                                    descricao: "Teclado Mecânico",
                                                                                                            quantidade: 15,
                                                                                                                    valor: 250.00
                                                                                                                        },
                                                                                                                            {
                                                                                                                                    codigo: 4,
                                                                                                                                            descricao: "Monitor 24",
                                                                                                                                                    quantidade: 8,
                                                                                                                                                            valor: 850.00
                                                                                                                                                                }
                                                                                                                                                                ];


                                                                                                                                                                // Alterar produto
                                                                                                                                                                function alterarProduto(codigo) {

                                                                                                                                                                    try {

                                                                                                                                                                            // Pegar os campos
                                                                                                                                                                                    const campoQuantidade = document.getElementById(
                                                                                                                                                                                                "novaQuantidade" + codigo
                                                                                                                                                                                                        );

                                                                                                                                                                                                                const campoValor = document.getElementById(
                                                                                                                                                                                                                            "novoValor" + codigo
                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                            // Procurar o produto
                                                                                                                                                                                                                                                    const produto = produtos.find(
                                                                                                                                                                                                                                                                produto => produto.codigo === codigo
                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                if (!produto) {
                                                                                                                                                                                                                                                                                            throw new Error("Produto não encontrado.");
                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                            // Alterar quantidade
                                                                                                                                                                                                                                                                                                                    if (campoQuantidade.value !== "") {

                                                                                                                                                                                                                                                                                                                                const novaQuantidade = Number(
                                                                                                                                                                                                                                                                                                                                                campoQuantidade.value
                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                        if (novaQuantidade < 1) {
                                                                                                                                                                                                                                                                                                                                                                                        throw new Error(
                                                                                                                                                                                                                                                                                                                                                                                                            "A quantidade deve ser maior que zero."
                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    produto.quantidade = novaQuantidade;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Alterar valor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (campoValor.value !== "") {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const novoValor = Number(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        campoValor.value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (novoValor < 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                throw new Error(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "O valor deve ser maior ou igual a zero."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            produto.valor = novoValor;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Atualizar quantidade na tela
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "quantidade" + codigo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ).textContent = produto.quantidade;


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Atualizar valor na tela
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "valor" + codigo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).textContent = produto.valor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .toFixed(2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .replace(".", ",");


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Limpar os campos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    campoQuantidade.value = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            campoValor.value = "";


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert("Produto atualizado com sucesso!");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (erro) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alert(erro.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }